/*
API цен и скидок

С помощью этих методов можно устанавливать цены и скидки. Максимум — 10 запросов за 6 секунд суммарно для всех методов раздела **Цены и скидки**.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricesapi

import (
	"encoding/json"
)

// checks if the ApiV1CalendarPromotionsDetailsGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV1CalendarPromotionsDetailsGet200ResponseData{}

// ApiV1CalendarPromotionsDetailsGet200ResponseData struct for ApiV1CalendarPromotionsDetailsGet200ResponseData
type ApiV1CalendarPromotionsDetailsGet200ResponseData struct {
	// Список акций
	Promotions []ApiV1CalendarPromotionsDetailsGet200ResponseDataPromotionsInner `json:"promotions,omitempty"`
}

// NewApiV1CalendarPromotionsDetailsGet200ResponseData instantiates a new ApiV1CalendarPromotionsDetailsGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1CalendarPromotionsDetailsGet200ResponseData() *ApiV1CalendarPromotionsDetailsGet200ResponseData {
	this := ApiV1CalendarPromotionsDetailsGet200ResponseData{}
	return &this
}

// NewApiV1CalendarPromotionsDetailsGet200ResponseDataWithDefaults instantiates a new ApiV1CalendarPromotionsDetailsGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1CalendarPromotionsDetailsGet200ResponseDataWithDefaults() *ApiV1CalendarPromotionsDetailsGet200ResponseData {
	this := ApiV1CalendarPromotionsDetailsGet200ResponseData{}
	return &this
}

// GetPromotions returns the Promotions field value if set, zero value otherwise.
func (o *ApiV1CalendarPromotionsDetailsGet200ResponseData) GetPromotions() []ApiV1CalendarPromotionsDetailsGet200ResponseDataPromotionsInner {
	if o == nil || IsNil(o.Promotions) {
		var ret []ApiV1CalendarPromotionsDetailsGet200ResponseDataPromotionsInner
		return ret
	}
	return o.Promotions
}

// GetPromotionsOk returns a tuple with the Promotions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1CalendarPromotionsDetailsGet200ResponseData) GetPromotionsOk() ([]ApiV1CalendarPromotionsDetailsGet200ResponseDataPromotionsInner, bool) {
	if o == nil || IsNil(o.Promotions) {
		return nil, false
	}
	return o.Promotions, true
}

// HasPromotions returns a boolean if a field has been set.
func (o *ApiV1CalendarPromotionsDetailsGet200ResponseData) HasPromotions() bool {
	if o != nil && !IsNil(o.Promotions) {
		return true
	}

	return false
}

// SetPromotions gets a reference to the given []ApiV1CalendarPromotionsDetailsGet200ResponseDataPromotionsInner and assigns it to the Promotions field.
func (o *ApiV1CalendarPromotionsDetailsGet200ResponseData) SetPromotions(v []ApiV1CalendarPromotionsDetailsGet200ResponseDataPromotionsInner) {
	o.Promotions = v
}

func (o ApiV1CalendarPromotionsDetailsGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV1CalendarPromotionsDetailsGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Promotions) {
		toSerialize["promotions"] = o.Promotions
	}
	return toSerialize, nil
}

type NullableApiV1CalendarPromotionsDetailsGet200ResponseData struct {
	value *ApiV1CalendarPromotionsDetailsGet200ResponseData
	isSet bool
}

func (v NullableApiV1CalendarPromotionsDetailsGet200ResponseData) Get() *ApiV1CalendarPromotionsDetailsGet200ResponseData {
	return v.value
}

func (v *NullableApiV1CalendarPromotionsDetailsGet200ResponseData) Set(val *ApiV1CalendarPromotionsDetailsGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1CalendarPromotionsDetailsGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1CalendarPromotionsDetailsGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1CalendarPromotionsDetailsGet200ResponseData(val *ApiV1CalendarPromotionsDetailsGet200ResponseData) *NullableApiV1CalendarPromotionsDetailsGet200ResponseData {
	return &NullableApiV1CalendarPromotionsDetailsGet200ResponseData{value: val, isSet: true}
}

func (v NullableApiV1CalendarPromotionsDetailsGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1CalendarPromotionsDetailsGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
