/*
API цен и скидок

С помощью этих методов можно устанавливать цены и скидки. Максимум — 10 запросов за 6 секунд суммарно для всех методов раздела **Цены и скидки**.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricesapi

import (
	"encoding/json"
)

// checks if the ApiV2HistoryTasksGet5XXResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV2HistoryTasksGet5XXResponse{}

// ApiV2HistoryTasksGet5XXResponse struct for ApiV2HistoryTasksGet5XXResponse
type ApiV2HistoryTasksGet5XXResponse struct {
	// Текст ошибки
	ErrorText *string `json:"errorText,omitempty"`
}

// NewApiV2HistoryTasksGet5XXResponse instantiates a new ApiV2HistoryTasksGet5XXResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV2HistoryTasksGet5XXResponse() *ApiV2HistoryTasksGet5XXResponse {
	this := ApiV2HistoryTasksGet5XXResponse{}
	return &this
}

// NewApiV2HistoryTasksGet5XXResponseWithDefaults instantiates a new ApiV2HistoryTasksGet5XXResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV2HistoryTasksGet5XXResponseWithDefaults() *ApiV2HistoryTasksGet5XXResponse {
	this := ApiV2HistoryTasksGet5XXResponse{}
	return &this
}

// GetErrorText returns the ErrorText field value if set, zero value otherwise.
func (o *ApiV2HistoryTasksGet5XXResponse) GetErrorText() string {
	if o == nil || IsNil(o.ErrorText) {
		var ret string
		return ret
	}
	return *o.ErrorText
}

// GetErrorTextOk returns a tuple with the ErrorText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV2HistoryTasksGet5XXResponse) GetErrorTextOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorText) {
		return nil, false
	}
	return o.ErrorText, true
}

// HasErrorText returns a boolean if a field has been set.
func (o *ApiV2HistoryTasksGet5XXResponse) HasErrorText() bool {
	if o != nil && !IsNil(o.ErrorText) {
		return true
	}

	return false
}

// SetErrorText gets a reference to the given string and assigns it to the ErrorText field.
func (o *ApiV2HistoryTasksGet5XXResponse) SetErrorText(v string) {
	o.ErrorText = &v
}

func (o ApiV2HistoryTasksGet5XXResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV2HistoryTasksGet5XXResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ErrorText) {
		toSerialize["errorText"] = o.ErrorText
	}
	return toSerialize, nil
}

type NullableApiV2HistoryTasksGet5XXResponse struct {
	value *ApiV2HistoryTasksGet5XXResponse
	isSet bool
}

func (v NullableApiV2HistoryTasksGet5XXResponse) Get() *ApiV2HistoryTasksGet5XXResponse {
	return v.value
}

func (v *NullableApiV2HistoryTasksGet5XXResponse) Set(val *ApiV2HistoryTasksGet5XXResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV2HistoryTasksGet5XXResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV2HistoryTasksGet5XXResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV2HistoryTasksGet5XXResponse(val *ApiV2HistoryTasksGet5XXResponse) *NullableApiV2HistoryTasksGet5XXResponse {
	return &NullableApiV2HistoryTasksGet5XXResponse{value: val, isSet: true}
}

func (v NullableApiV2HistoryTasksGet5XXResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV2HistoryTasksGet5XXResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
