/*
API цен и скидок

С помощью этих методов можно устанавливать цены и скидки. Максимум — 10 запросов за 6 секунд суммарно для всех методов раздела **Цены и скидки**.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricesapi

import (
	"encoding/json"
)

// checks if the SizeGood type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SizeGood{}

// SizeGood Информация о размере
type SizeGood struct {
	// Артикул Wildberries
	NmID *int32 `json:"nmID,omitempty"`
	// ID размера. Можно получить с помощью метода [Получение списка товаров по артикулам](./#tag/Spiski-tovarov/paths/~1api~1v2~1list~1goods~1filter/get), поле `sizeID`. В методах контента это поле `chrtID`
	SizeID *int32 `json:"sizeID,omitempty"`
	// Артикул продавца
	VendorCode *string `json:"vendorCode,omitempty"`
	// Цена
	Price *int32 `json:"price,omitempty"`
	// Валюта, по стандарту ISO 4217
	CurrencyIsoCode4217 *string `json:"currencyIsoCode4217,omitempty"`
	// Цена со скидкой
	DiscountedPrice *float32 `json:"discountedPrice,omitempty"`
	// Скидка, %
	Discount *int32 `json:"discount,omitempty"`
	// Размер товара
	TechSizeName *string `json:"techSizeName,omitempty"`
	// Можно ли устанавливать цены отдельно для разных размеров: `true` — можно, `false` — нельзя. Эта возможность зависит от категории товара
	EditableSizePrice *bool `json:"editableSizePrice,omitempty"`
}

// NewSizeGood instantiates a new SizeGood object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSizeGood() *SizeGood {
	this := SizeGood{}
	return &this
}

// NewSizeGoodWithDefaults instantiates a new SizeGood object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSizeGoodWithDefaults() *SizeGood {
	this := SizeGood{}
	return &this
}

// GetNmID returns the NmID field value if set, zero value otherwise.
func (o *SizeGood) GetNmID() int32 {
	if o == nil || IsNil(o.NmID) {
		var ret int32
		return ret
	}
	return *o.NmID
}

// GetNmIDOk returns a tuple with the NmID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SizeGood) GetNmIDOk() (*int32, bool) {
	if o == nil || IsNil(o.NmID) {
		return nil, false
	}
	return o.NmID, true
}

// HasNmID returns a boolean if a field has been set.
func (o *SizeGood) HasNmID() bool {
	if o != nil && !IsNil(o.NmID) {
		return true
	}

	return false
}

// SetNmID gets a reference to the given int32 and assigns it to the NmID field.
func (o *SizeGood) SetNmID(v int32) {
	o.NmID = &v
}

// GetSizeID returns the SizeID field value if set, zero value otherwise.
func (o *SizeGood) GetSizeID() int32 {
	if o == nil || IsNil(o.SizeID) {
		var ret int32
		return ret
	}
	return *o.SizeID
}

// GetSizeIDOk returns a tuple with the SizeID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SizeGood) GetSizeIDOk() (*int32, bool) {
	if o == nil || IsNil(o.SizeID) {
		return nil, false
	}
	return o.SizeID, true
}

// HasSizeID returns a boolean if a field has been set.
func (o *SizeGood) HasSizeID() bool {
	if o != nil && !IsNil(o.SizeID) {
		return true
	}

	return false
}

// SetSizeID gets a reference to the given int32 and assigns it to the SizeID field.
func (o *SizeGood) SetSizeID(v int32) {
	o.SizeID = &v
}

// GetVendorCode returns the VendorCode field value if set, zero value otherwise.
func (o *SizeGood) GetVendorCode() string {
	if o == nil || IsNil(o.VendorCode) {
		var ret string
		return ret
	}
	return *o.VendorCode
}

// GetVendorCodeOk returns a tuple with the VendorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SizeGood) GetVendorCodeOk() (*string, bool) {
	if o == nil || IsNil(o.VendorCode) {
		return nil, false
	}
	return o.VendorCode, true
}

// HasVendorCode returns a boolean if a field has been set.
func (o *SizeGood) HasVendorCode() bool {
	if o != nil && !IsNil(o.VendorCode) {
		return true
	}

	return false
}

// SetVendorCode gets a reference to the given string and assigns it to the VendorCode field.
func (o *SizeGood) SetVendorCode(v string) {
	o.VendorCode = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *SizeGood) GetPrice() int32 {
	if o == nil || IsNil(o.Price) {
		var ret int32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SizeGood) GetPriceOk() (*int32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *SizeGood) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given int32 and assigns it to the Price field.
func (o *SizeGood) SetPrice(v int32) {
	o.Price = &v
}

// GetCurrencyIsoCode4217 returns the CurrencyIsoCode4217 field value if set, zero value otherwise.
func (o *SizeGood) GetCurrencyIsoCode4217() string {
	if o == nil || IsNil(o.CurrencyIsoCode4217) {
		var ret string
		return ret
	}
	return *o.CurrencyIsoCode4217
}

// GetCurrencyIsoCode4217Ok returns a tuple with the CurrencyIsoCode4217 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SizeGood) GetCurrencyIsoCode4217Ok() (*string, bool) {
	if o == nil || IsNil(o.CurrencyIsoCode4217) {
		return nil, false
	}
	return o.CurrencyIsoCode4217, true
}

// HasCurrencyIsoCode4217 returns a boolean if a field has been set.
func (o *SizeGood) HasCurrencyIsoCode4217() bool {
	if o != nil && !IsNil(o.CurrencyIsoCode4217) {
		return true
	}

	return false
}

// SetCurrencyIsoCode4217 gets a reference to the given string and assigns it to the CurrencyIsoCode4217 field.
func (o *SizeGood) SetCurrencyIsoCode4217(v string) {
	o.CurrencyIsoCode4217 = &v
}

// GetDiscountedPrice returns the DiscountedPrice field value if set, zero value otherwise.
func (o *SizeGood) GetDiscountedPrice() float32 {
	if o == nil || IsNil(o.DiscountedPrice) {
		var ret float32
		return ret
	}
	return *o.DiscountedPrice
}

// GetDiscountedPriceOk returns a tuple with the DiscountedPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SizeGood) GetDiscountedPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.DiscountedPrice) {
		return nil, false
	}
	return o.DiscountedPrice, true
}

// HasDiscountedPrice returns a boolean if a field has been set.
func (o *SizeGood) HasDiscountedPrice() bool {
	if o != nil && !IsNil(o.DiscountedPrice) {
		return true
	}

	return false
}

// SetDiscountedPrice gets a reference to the given float32 and assigns it to the DiscountedPrice field.
func (o *SizeGood) SetDiscountedPrice(v float32) {
	o.DiscountedPrice = &v
}

// GetDiscount returns the Discount field value if set, zero value otherwise.
func (o *SizeGood) GetDiscount() int32 {
	if o == nil || IsNil(o.Discount) {
		var ret int32
		return ret
	}
	return *o.Discount
}

// GetDiscountOk returns a tuple with the Discount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SizeGood) GetDiscountOk() (*int32, bool) {
	if o == nil || IsNil(o.Discount) {
		return nil, false
	}
	return o.Discount, true
}

// HasDiscount returns a boolean if a field has been set.
func (o *SizeGood) HasDiscount() bool {
	if o != nil && !IsNil(o.Discount) {
		return true
	}

	return false
}

// SetDiscount gets a reference to the given int32 and assigns it to the Discount field.
func (o *SizeGood) SetDiscount(v int32) {
	o.Discount = &v
}

// GetTechSizeName returns the TechSizeName field value if set, zero value otherwise.
func (o *SizeGood) GetTechSizeName() string {
	if o == nil || IsNil(o.TechSizeName) {
		var ret string
		return ret
	}
	return *o.TechSizeName
}

// GetTechSizeNameOk returns a tuple with the TechSizeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SizeGood) GetTechSizeNameOk() (*string, bool) {
	if o == nil || IsNil(o.TechSizeName) {
		return nil, false
	}
	return o.TechSizeName, true
}

// HasTechSizeName returns a boolean if a field has been set.
func (o *SizeGood) HasTechSizeName() bool {
	if o != nil && !IsNil(o.TechSizeName) {
		return true
	}

	return false
}

// SetTechSizeName gets a reference to the given string and assigns it to the TechSizeName field.
func (o *SizeGood) SetTechSizeName(v string) {
	o.TechSizeName = &v
}

// GetEditableSizePrice returns the EditableSizePrice field value if set, zero value otherwise.
func (o *SizeGood) GetEditableSizePrice() bool {
	if o == nil || IsNil(o.EditableSizePrice) {
		var ret bool
		return ret
	}
	return *o.EditableSizePrice
}

// GetEditableSizePriceOk returns a tuple with the EditableSizePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SizeGood) GetEditableSizePriceOk() (*bool, bool) {
	if o == nil || IsNil(o.EditableSizePrice) {
		return nil, false
	}
	return o.EditableSizePrice, true
}

// HasEditableSizePrice returns a boolean if a field has been set.
func (o *SizeGood) HasEditableSizePrice() bool {
	if o != nil && !IsNil(o.EditableSizePrice) {
		return true
	}

	return false
}

// SetEditableSizePrice gets a reference to the given bool and assigns it to the EditableSizePrice field.
func (o *SizeGood) SetEditableSizePrice(v bool) {
	o.EditableSizePrice = &v
}

func (o SizeGood) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SizeGood) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NmID) {
		toSerialize["nmID"] = o.NmID
	}
	if !IsNil(o.SizeID) {
		toSerialize["sizeID"] = o.SizeID
	}
	if !IsNil(o.VendorCode) {
		toSerialize["vendorCode"] = o.VendorCode
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	if !IsNil(o.CurrencyIsoCode4217) {
		toSerialize["currencyIsoCode4217"] = o.CurrencyIsoCode4217
	}
	if !IsNil(o.DiscountedPrice) {
		toSerialize["discountedPrice"] = o.DiscountedPrice
	}
	if !IsNil(o.Discount) {
		toSerialize["discount"] = o.Discount
	}
	if !IsNil(o.TechSizeName) {
		toSerialize["techSizeName"] = o.TechSizeName
	}
	if !IsNil(o.EditableSizePrice) {
		toSerialize["editableSizePrice"] = o.EditableSizePrice
	}
	return toSerialize, nil
}

type NullableSizeGood struct {
	value *SizeGood
	isSet bool
}

func (v NullableSizeGood) Get() *SizeGood {
	return v.value
}

func (v *NullableSizeGood) Set(val *SizeGood) {
	v.value = val
	v.isSet = true
}

func (v NullableSizeGood) IsSet() bool {
	return v.isSet
}

func (v *NullableSizeGood) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSizeGood(val *SizeGood) *NullableSizeGood {
	return &NullableSizeGood{value: val, isSet: true}
}

func (v NullableSizeGood) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSizeGood) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
