/*
API цен и скидок

С помощью этих методов можно устанавливать цены и скидки. Максимум — 10 запросов за 6 секунд суммарно для всех методов раздела **Цены и скидки**.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricesapi

import (
	"encoding/json"
)

// checks if the GoodBufferHistory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GoodBufferHistory{}

// GoodBufferHistory struct for GoodBufferHistory
type GoodBufferHistory struct {
	// Артикул Wildberries
	NmID *int32 `json:"nmID,omitempty"`
	// Артикул продавца
	VendorCode *string `json:"vendorCode,omitempty"`
	// ID размера. В методах контента это поле `chrtID`
	SizeID *int32 `json:"sizeID,omitempty"`
	// Размер
	TechSizeName *string `json:"techSizeName,omitempty"`
	// Цена
	Price *int32 `json:"price,omitempty"`
	// Валюта, по стандарту ISO 4217
	CurrencyIsoCode4217 *string `json:"currencyIsoCode4217,omitempty"`
	// Скидка, %
	Discount *int32 `json:"discount,omitempty"`
	// Статус товара: `1` — в обработке
	Status *int32 `json:"status,omitempty"`
	// Текст ошибки
	ErrorText *string `json:"errorText,omitempty"`
}

// NewGoodBufferHistory instantiates a new GoodBufferHistory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoodBufferHistory() *GoodBufferHistory {
	this := GoodBufferHistory{}
	return &this
}

// NewGoodBufferHistoryWithDefaults instantiates a new GoodBufferHistory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoodBufferHistoryWithDefaults() *GoodBufferHistory {
	this := GoodBufferHistory{}
	return &this
}

// GetNmID returns the NmID field value if set, zero value otherwise.
func (o *GoodBufferHistory) GetNmID() int32 {
	if o == nil || IsNil(o.NmID) {
		var ret int32
		return ret
	}
	return *o.NmID
}

// GetNmIDOk returns a tuple with the NmID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoodBufferHistory) GetNmIDOk() (*int32, bool) {
	if o == nil || IsNil(o.NmID) {
		return nil, false
	}
	return o.NmID, true
}

// HasNmID returns a boolean if a field has been set.
func (o *GoodBufferHistory) HasNmID() bool {
	if o != nil && !IsNil(o.NmID) {
		return true
	}

	return false
}

// SetNmID gets a reference to the given int32 and assigns it to the NmID field.
func (o *GoodBufferHistory) SetNmID(v int32) {
	o.NmID = &v
}

// GetVendorCode returns the VendorCode field value if set, zero value otherwise.
func (o *GoodBufferHistory) GetVendorCode() string {
	if o == nil || IsNil(o.VendorCode) {
		var ret string
		return ret
	}
	return *o.VendorCode
}

// GetVendorCodeOk returns a tuple with the VendorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoodBufferHistory) GetVendorCodeOk() (*string, bool) {
	if o == nil || IsNil(o.VendorCode) {
		return nil, false
	}
	return o.VendorCode, true
}

// HasVendorCode returns a boolean if a field has been set.
func (o *GoodBufferHistory) HasVendorCode() bool {
	if o != nil && !IsNil(o.VendorCode) {
		return true
	}

	return false
}

// SetVendorCode gets a reference to the given string and assigns it to the VendorCode field.
func (o *GoodBufferHistory) SetVendorCode(v string) {
	o.VendorCode = &v
}

// GetSizeID returns the SizeID field value if set, zero value otherwise.
func (o *GoodBufferHistory) GetSizeID() int32 {
	if o == nil || IsNil(o.SizeID) {
		var ret int32
		return ret
	}
	return *o.SizeID
}

// GetSizeIDOk returns a tuple with the SizeID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoodBufferHistory) GetSizeIDOk() (*int32, bool) {
	if o == nil || IsNil(o.SizeID) {
		return nil, false
	}
	return o.SizeID, true
}

// HasSizeID returns a boolean if a field has been set.
func (o *GoodBufferHistory) HasSizeID() bool {
	if o != nil && !IsNil(o.SizeID) {
		return true
	}

	return false
}

// SetSizeID gets a reference to the given int32 and assigns it to the SizeID field.
func (o *GoodBufferHistory) SetSizeID(v int32) {
	o.SizeID = &v
}

// GetTechSizeName returns the TechSizeName field value if set, zero value otherwise.
func (o *GoodBufferHistory) GetTechSizeName() string {
	if o == nil || IsNil(o.TechSizeName) {
		var ret string
		return ret
	}
	return *o.TechSizeName
}

// GetTechSizeNameOk returns a tuple with the TechSizeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoodBufferHistory) GetTechSizeNameOk() (*string, bool) {
	if o == nil || IsNil(o.TechSizeName) {
		return nil, false
	}
	return o.TechSizeName, true
}

// HasTechSizeName returns a boolean if a field has been set.
func (o *GoodBufferHistory) HasTechSizeName() bool {
	if o != nil && !IsNil(o.TechSizeName) {
		return true
	}

	return false
}

// SetTechSizeName gets a reference to the given string and assigns it to the TechSizeName field.
func (o *GoodBufferHistory) SetTechSizeName(v string) {
	o.TechSizeName = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *GoodBufferHistory) GetPrice() int32 {
	if o == nil || IsNil(o.Price) {
		var ret int32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoodBufferHistory) GetPriceOk() (*int32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *GoodBufferHistory) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given int32 and assigns it to the Price field.
func (o *GoodBufferHistory) SetPrice(v int32) {
	o.Price = &v
}

// GetCurrencyIsoCode4217 returns the CurrencyIsoCode4217 field value if set, zero value otherwise.
func (o *GoodBufferHistory) GetCurrencyIsoCode4217() string {
	if o == nil || IsNil(o.CurrencyIsoCode4217) {
		var ret string
		return ret
	}
	return *o.CurrencyIsoCode4217
}

// GetCurrencyIsoCode4217Ok returns a tuple with the CurrencyIsoCode4217 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoodBufferHistory) GetCurrencyIsoCode4217Ok() (*string, bool) {
	if o == nil || IsNil(o.CurrencyIsoCode4217) {
		return nil, false
	}
	return o.CurrencyIsoCode4217, true
}

// HasCurrencyIsoCode4217 returns a boolean if a field has been set.
func (o *GoodBufferHistory) HasCurrencyIsoCode4217() bool {
	if o != nil && !IsNil(o.CurrencyIsoCode4217) {
		return true
	}

	return false
}

// SetCurrencyIsoCode4217 gets a reference to the given string and assigns it to the CurrencyIsoCode4217 field.
func (o *GoodBufferHistory) SetCurrencyIsoCode4217(v string) {
	o.CurrencyIsoCode4217 = &v
}

// GetDiscount returns the Discount field value if set, zero value otherwise.
func (o *GoodBufferHistory) GetDiscount() int32 {
	if o == nil || IsNil(o.Discount) {
		var ret int32
		return ret
	}
	return *o.Discount
}

// GetDiscountOk returns a tuple with the Discount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoodBufferHistory) GetDiscountOk() (*int32, bool) {
	if o == nil || IsNil(o.Discount) {
		return nil, false
	}
	return o.Discount, true
}

// HasDiscount returns a boolean if a field has been set.
func (o *GoodBufferHistory) HasDiscount() bool {
	if o != nil && !IsNil(o.Discount) {
		return true
	}

	return false
}

// SetDiscount gets a reference to the given int32 and assigns it to the Discount field.
func (o *GoodBufferHistory) SetDiscount(v int32) {
	o.Discount = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GoodBufferHistory) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoodBufferHistory) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GoodBufferHistory) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *GoodBufferHistory) SetStatus(v int32) {
	o.Status = &v
}

// GetErrorText returns the ErrorText field value if set, zero value otherwise.
func (o *GoodBufferHistory) GetErrorText() string {
	if o == nil || IsNil(o.ErrorText) {
		var ret string
		return ret
	}
	return *o.ErrorText
}

// GetErrorTextOk returns a tuple with the ErrorText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoodBufferHistory) GetErrorTextOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorText) {
		return nil, false
	}
	return o.ErrorText, true
}

// HasErrorText returns a boolean if a field has been set.
func (o *GoodBufferHistory) HasErrorText() bool {
	if o != nil && !IsNil(o.ErrorText) {
		return true
	}

	return false
}

// SetErrorText gets a reference to the given string and assigns it to the ErrorText field.
func (o *GoodBufferHistory) SetErrorText(v string) {
	o.ErrorText = &v
}

func (o GoodBufferHistory) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GoodBufferHistory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NmID) {
		toSerialize["nmID"] = o.NmID
	}
	if !IsNil(o.VendorCode) {
		toSerialize["vendorCode"] = o.VendorCode
	}
	if !IsNil(o.SizeID) {
		toSerialize["sizeID"] = o.SizeID
	}
	if !IsNil(o.TechSizeName) {
		toSerialize["techSizeName"] = o.TechSizeName
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	if !IsNil(o.CurrencyIsoCode4217) {
		toSerialize["currencyIsoCode4217"] = o.CurrencyIsoCode4217
	}
	if !IsNil(o.Discount) {
		toSerialize["discount"] = o.Discount
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.ErrorText) {
		toSerialize["errorText"] = o.ErrorText
	}
	return toSerialize, nil
}

type NullableGoodBufferHistory struct {
	value *GoodBufferHistory
	isSet bool
}

func (v NullableGoodBufferHistory) Get() *GoodBufferHistory {
	return v.value
}

func (v *NullableGoodBufferHistory) Set(val *GoodBufferHistory) {
	v.value = val
	v.isSet = true
}

func (v NullableGoodBufferHistory) IsSet() bool {
	return v.isSet
}

func (v *NullableGoodBufferHistory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoodBufferHistory(val *GoodBufferHistory) *NullableGoodBufferHistory {
	return &NullableGoodBufferHistory{value: val, isSet: true}
}

func (v NullableGoodBufferHistory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoodBufferHistory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
