/*
API цен и скидок

С помощью этих методов можно устанавливать цены и скидки. Максимум — 10 запросов за 6 секунд суммарно для всех методов раздела **Цены и скидки**.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricesapi

import (
	"encoding/json"
)

// checks if the ApiV2HistoryTasksGet4XXResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV2HistoryTasksGet4XXResponse{}

// ApiV2HistoryTasksGet4XXResponse struct for ApiV2HistoryTasksGet4XXResponse
type ApiV2HistoryTasksGet4XXResponse struct {
	// Текст ошибки
	ErrorText *string `json:"errorText,omitempty"`
}

// NewApiV2HistoryTasksGet4XXResponse instantiates a new ApiV2HistoryTasksGet4XXResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV2HistoryTasksGet4XXResponse() *ApiV2HistoryTasksGet4XXResponse {
	this := ApiV2HistoryTasksGet4XXResponse{}
	return &this
}

// NewApiV2HistoryTasksGet4XXResponseWithDefaults instantiates a new ApiV2HistoryTasksGet4XXResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV2HistoryTasksGet4XXResponseWithDefaults() *ApiV2HistoryTasksGet4XXResponse {
	this := ApiV2HistoryTasksGet4XXResponse{}
	return &this
}

// GetErrorText returns the ErrorText field value if set, zero value otherwise.
func (o *ApiV2HistoryTasksGet4XXResponse) GetErrorText() string {
	if o == nil || IsNil(o.ErrorText) {
		var ret string
		return ret
	}
	return *o.ErrorText
}

// GetErrorTextOk returns a tuple with the ErrorText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV2HistoryTasksGet4XXResponse) GetErrorTextOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorText) {
		return nil, false
	}
	return o.ErrorText, true
}

// HasErrorText returns a boolean if a field has been set.
func (o *ApiV2HistoryTasksGet4XXResponse) HasErrorText() bool {
	if o != nil && !IsNil(o.ErrorText) {
		return true
	}

	return false
}

// SetErrorText gets a reference to the given string and assigns it to the ErrorText field.
func (o *ApiV2HistoryTasksGet4XXResponse) SetErrorText(v string) {
	o.ErrorText = &v
}

func (o ApiV2HistoryTasksGet4XXResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV2HistoryTasksGet4XXResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ErrorText) {
		toSerialize["errorText"] = o.ErrorText
	}
	return toSerialize, nil
}

type NullableApiV2HistoryTasksGet4XXResponse struct {
	value *ApiV2HistoryTasksGet4XXResponse
	isSet bool
}

func (v NullableApiV2HistoryTasksGet4XXResponse) Get() *ApiV2HistoryTasksGet4XXResponse {
	return v.value
}

func (v *NullableApiV2HistoryTasksGet4XXResponse) Set(val *ApiV2HistoryTasksGet4XXResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV2HistoryTasksGet4XXResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV2HistoryTasksGet4XXResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV2HistoryTasksGet4XXResponse(val *ApiV2HistoryTasksGet4XXResponse) *NullableApiV2HistoryTasksGet4XXResponse {
	return &NullableApiV2HistoryTasksGet4XXResponse{value: val, isSet: true}
}

func (v NullableApiV2HistoryTasksGet4XXResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV2HistoryTasksGet4XXResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
