/*
API цен и скидок

С помощью этих методов можно устанавливать цены и скидки. Максимум — 10 запросов за 6 секунд суммарно для всех методов раздела **Цены и скидки**.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pricesapi

import (
	"encoding/json"
)

// checks if the ApiV1CalendarPromotionsNomenclaturesGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV1CalendarPromotionsNomenclaturesGet200Response{}

// ApiV1CalendarPromotionsNomenclaturesGet200Response struct for ApiV1CalendarPromotionsNomenclaturesGet200Response
type ApiV1CalendarPromotionsNomenclaturesGet200Response struct {
	Data *ApiV1CalendarPromotionsNomenclaturesGet200ResponseData `json:"data,omitempty"`
}

// NewApiV1CalendarPromotionsNomenclaturesGet200Response instantiates a new ApiV1CalendarPromotionsNomenclaturesGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1CalendarPromotionsNomenclaturesGet200Response() *ApiV1CalendarPromotionsNomenclaturesGet200Response {
	this := ApiV1CalendarPromotionsNomenclaturesGet200Response{}
	return &this
}

// NewApiV1CalendarPromotionsNomenclaturesGet200ResponseWithDefaults instantiates a new ApiV1CalendarPromotionsNomenclaturesGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1CalendarPromotionsNomenclaturesGet200ResponseWithDefaults() *ApiV1CalendarPromotionsNomenclaturesGet200Response {
	this := ApiV1CalendarPromotionsNomenclaturesGet200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ApiV1CalendarPromotionsNomenclaturesGet200Response) GetData() ApiV1CalendarPromotionsNomenclaturesGet200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret ApiV1CalendarPromotionsNomenclaturesGet200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1CalendarPromotionsNomenclaturesGet200Response) GetDataOk() (*ApiV1CalendarPromotionsNomenclaturesGet200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ApiV1CalendarPromotionsNomenclaturesGet200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ApiV1CalendarPromotionsNomenclaturesGet200ResponseData and assigns it to the Data field.
func (o *ApiV1CalendarPromotionsNomenclaturesGet200Response) SetData(v ApiV1CalendarPromotionsNomenclaturesGet200ResponseData) {
	o.Data = &v
}

func (o ApiV1CalendarPromotionsNomenclaturesGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV1CalendarPromotionsNomenclaturesGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableApiV1CalendarPromotionsNomenclaturesGet200Response struct {
	value *ApiV1CalendarPromotionsNomenclaturesGet200Response
	isSet bool
}

func (v NullableApiV1CalendarPromotionsNomenclaturesGet200Response) Get() *ApiV1CalendarPromotionsNomenclaturesGet200Response {
	return v.value
}

func (v *NullableApiV1CalendarPromotionsNomenclaturesGet200Response) Set(val *ApiV1CalendarPromotionsNomenclaturesGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1CalendarPromotionsNomenclaturesGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1CalendarPromotionsNomenclaturesGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1CalendarPromotionsNomenclaturesGet200Response(val *ApiV1CalendarPromotionsNomenclaturesGet200Response) *NullableApiV1CalendarPromotionsNomenclaturesGet200Response {
	return &NullableApiV1CalendarPromotionsNomenclaturesGet200Response{value: val, isSet: true}
}

func (v NullableApiV1CalendarPromotionsNomenclaturesGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1CalendarPromotionsNomenclaturesGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
