POST localhost:8080/api/v1/telegram/webhooks
Content-Type: application/json

{
  "update_id": 17373773737,
  "my_chat_member": {
    "chat": {
      "id": -1002183228927,
      "type": "channel",
      "title": "Test Channel",
      "username": "test_channel"
    },
    "from": {
      "id": 1079068782
    },
    "new_chat_member": {
      "can_post_messages": true,
      "status": "administrator",
      "user": {
        "id": 7141486456
      }
    }
  }
}


###
