/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ContentV2CardsUploadAddPostRequestCardsToAddInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentV2CardsUploadAddPostRequestCardsToAddInner{}

// ContentV2CardsUploadAddPostRequestCardsToAddInner struct for ContentV2CardsUploadAddPostRequestCardsToAddInner
type ContentV2CardsUploadAddPostRequestCardsToAddInner struct {
	// Бренд
	Brand *string `json:"brand,omitempty"`
	// Артикул продавца
	VendorCode string `json:"vendorCode"`
	// Наименование товара
	Title *string `json:"title,omitempty"`
	// Описание товара. Максимальное количество символов зависит от категории товара. Стандарт — 2000, минимум — 1000, максимум — 5000.<br> Подробно о правилах описания в **Правилах заполнения карточки товара** в разделе [Инструкции](https://seller.wildberries.ru/help-center/article/A-113#описание) на портале продавцов.
	Description *string                                                      `json:"description,omitempty"`
	Dimensions  *ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions `json:"dimensions,omitempty"`
	// Характеристики товара
	Characteristics []ContentV2CardsUploadAddPostRequestCardsToAddInnerCharacteristicsInner `json:"characteristics,omitempty"`
	// Массив с размерами. <br>  Если для размерного товара (обувь, одежда и др.) не указать этот массив, то системой в карточке он будет сгенерирован автоматически с `techSize` = \"A\" и `wbSize` = \"1\" и баркодом.
	Sizes []ContentV2CardsUploadAddPostRequestCardsToAddInnerSizesInner `json:"sizes,omitempty"`
}

type _ContentV2CardsUploadAddPostRequestCardsToAddInner ContentV2CardsUploadAddPostRequestCardsToAddInner

// NewContentV2CardsUploadAddPostRequestCardsToAddInner instantiates a new ContentV2CardsUploadAddPostRequestCardsToAddInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentV2CardsUploadAddPostRequestCardsToAddInner(vendorCode string) *ContentV2CardsUploadAddPostRequestCardsToAddInner {
	this := ContentV2CardsUploadAddPostRequestCardsToAddInner{}
	this.VendorCode = vendorCode
	return &this
}

// NewContentV2CardsUploadAddPostRequestCardsToAddInnerWithDefaults instantiates a new ContentV2CardsUploadAddPostRequestCardsToAddInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentV2CardsUploadAddPostRequestCardsToAddInnerWithDefaults() *ContentV2CardsUploadAddPostRequestCardsToAddInner {
	this := ContentV2CardsUploadAddPostRequestCardsToAddInner{}
	return &this
}

// GetBrand returns the Brand field value if set, zero value otherwise.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) GetBrand() string {
	if o == nil || IsNil(o.Brand) {
		var ret string
		return ret
	}
	return *o.Brand
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) GetBrandOk() (*string, bool) {
	if o == nil || IsNil(o.Brand) {
		return nil, false
	}
	return o.Brand, true
}

// HasBrand returns a boolean if a field has been set.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) HasBrand() bool {
	if o != nil && !IsNil(o.Brand) {
		return true
	}

	return false
}

// SetBrand gets a reference to the given string and assigns it to the Brand field.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) SetBrand(v string) {
	o.Brand = &v
}

// GetVendorCode returns the VendorCode field value
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) GetVendorCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VendorCode
}

// GetVendorCodeOk returns a tuple with the VendorCode field value
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) GetVendorCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VendorCode, true
}

// SetVendorCode sets field value
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) SetVendorCode(v string) {
	o.VendorCode = v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) SetDescription(v string) {
	o.Description = &v
}

// GetDimensions returns the Dimensions field value if set, zero value otherwise.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) GetDimensions() ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions {
	if o == nil || IsNil(o.Dimensions) {
		var ret ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions
		return ret
	}
	return *o.Dimensions
}

// GetDimensionsOk returns a tuple with the Dimensions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) GetDimensionsOk() (*ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions, bool) {
	if o == nil || IsNil(o.Dimensions) {
		return nil, false
	}
	return o.Dimensions, true
}

// HasDimensions returns a boolean if a field has been set.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) HasDimensions() bool {
	if o != nil && !IsNil(o.Dimensions) {
		return true
	}

	return false
}

// SetDimensions gets a reference to the given ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions and assigns it to the Dimensions field.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) SetDimensions(v ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) {
	o.Dimensions = &v
}

// GetCharacteristics returns the Characteristics field value if set, zero value otherwise.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) GetCharacteristics() []ContentV2CardsUploadAddPostRequestCardsToAddInnerCharacteristicsInner {
	if o == nil || IsNil(o.Characteristics) {
		var ret []ContentV2CardsUploadAddPostRequestCardsToAddInnerCharacteristicsInner
		return ret
	}
	return o.Characteristics
}

// GetCharacteristicsOk returns a tuple with the Characteristics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) GetCharacteristicsOk() ([]ContentV2CardsUploadAddPostRequestCardsToAddInnerCharacteristicsInner, bool) {
	if o == nil || IsNil(o.Characteristics) {
		return nil, false
	}
	return o.Characteristics, true
}

// HasCharacteristics returns a boolean if a field has been set.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) HasCharacteristics() bool {
	if o != nil && !IsNil(o.Characteristics) {
		return true
	}

	return false
}

// SetCharacteristics gets a reference to the given []ContentV2CardsUploadAddPostRequestCardsToAddInnerCharacteristicsInner and assigns it to the Characteristics field.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) SetCharacteristics(v []ContentV2CardsUploadAddPostRequestCardsToAddInnerCharacteristicsInner) {
	o.Characteristics = v
}

// GetSizes returns the Sizes field value if set, zero value otherwise.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) GetSizes() []ContentV2CardsUploadAddPostRequestCardsToAddInnerSizesInner {
	if o == nil || IsNil(o.Sizes) {
		var ret []ContentV2CardsUploadAddPostRequestCardsToAddInnerSizesInner
		return ret
	}
	return o.Sizes
}

// GetSizesOk returns a tuple with the Sizes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) GetSizesOk() ([]ContentV2CardsUploadAddPostRequestCardsToAddInnerSizesInner, bool) {
	if o == nil || IsNil(o.Sizes) {
		return nil, false
	}
	return o.Sizes, true
}

// HasSizes returns a boolean if a field has been set.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) HasSizes() bool {
	if o != nil && !IsNil(o.Sizes) {
		return true
	}

	return false
}

// SetSizes gets a reference to the given []ContentV2CardsUploadAddPostRequestCardsToAddInnerSizesInner and assigns it to the Sizes field.
func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) SetSizes(v []ContentV2CardsUploadAddPostRequestCardsToAddInnerSizesInner) {
	o.Sizes = v
}

func (o ContentV2CardsUploadAddPostRequestCardsToAddInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentV2CardsUploadAddPostRequestCardsToAddInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Brand) {
		toSerialize["brand"] = o.Brand
	}
	toSerialize["vendorCode"] = o.VendorCode
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Dimensions) {
		toSerialize["dimensions"] = o.Dimensions
	}
	if !IsNil(o.Characteristics) {
		toSerialize["characteristics"] = o.Characteristics
	}
	if !IsNil(o.Sizes) {
		toSerialize["sizes"] = o.Sizes
	}
	return toSerialize, nil
}

func (o *ContentV2CardsUploadAddPostRequestCardsToAddInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"vendorCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContentV2CardsUploadAddPostRequestCardsToAddInner := _ContentV2CardsUploadAddPostRequestCardsToAddInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContentV2CardsUploadAddPostRequestCardsToAddInner)

	if err != nil {
		return err
	}

	*o = ContentV2CardsUploadAddPostRequestCardsToAddInner(varContentV2CardsUploadAddPostRequestCardsToAddInner)

	return err
}

type NullableContentV2CardsUploadAddPostRequestCardsToAddInner struct {
	value *ContentV2CardsUploadAddPostRequestCardsToAddInner
	isSet bool
}

func (v NullableContentV2CardsUploadAddPostRequestCardsToAddInner) Get() *ContentV2CardsUploadAddPostRequestCardsToAddInner {
	return v.value
}

func (v *NullableContentV2CardsUploadAddPostRequestCardsToAddInner) Set(val *ContentV2CardsUploadAddPostRequestCardsToAddInner) {
	v.value = val
	v.isSet = true
}

func (v NullableContentV2CardsUploadAddPostRequestCardsToAddInner) IsSet() bool {
	return v.isSet
}

func (v *NullableContentV2CardsUploadAddPostRequestCardsToAddInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentV2CardsUploadAddPostRequestCardsToAddInner(val *ContentV2CardsUploadAddPostRequestCardsToAddInner) *NullableContentV2CardsUploadAddPostRequestCardsToAddInner {
	return &NullableContentV2CardsUploadAddPostRequestCardsToAddInner{value: val, isSet: true}
}

func (v NullableContentV2CardsUploadAddPostRequestCardsToAddInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentV2CardsUploadAddPostRequestCardsToAddInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
