/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ContentV2CardsUpdatePostRequestInnerCharacteristicsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentV2CardsUpdatePostRequestInnerCharacteristicsInner{}

// ContentV2CardsUpdatePostRequestInnerCharacteristicsInner struct for ContentV2CardsUpdatePostRequestInnerCharacteristicsInner
type ContentV2CardsUpdatePostRequestInnerCharacteristicsInner struct {
	// ShopID характеристики
	Id *int32 `json:"id,omitempty"`
	// Значение характеристики. Тип значения зависит от типа характеристики.
	Value interface{} `json:"value,omitempty"`
}

// NewContentV2CardsUpdatePostRequestInnerCharacteristicsInner instantiates a new ContentV2CardsUpdatePostRequestInnerCharacteristicsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentV2CardsUpdatePostRequestInnerCharacteristicsInner() *ContentV2CardsUpdatePostRequestInnerCharacteristicsInner {
	this := ContentV2CardsUpdatePostRequestInnerCharacteristicsInner{}
	return &this
}

// NewContentV2CardsUpdatePostRequestInnerCharacteristicsInnerWithDefaults instantiates a new ContentV2CardsUpdatePostRequestInnerCharacteristicsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentV2CardsUpdatePostRequestInnerCharacteristicsInnerWithDefaults() *ContentV2CardsUpdatePostRequestInnerCharacteristicsInner {
	this := ContentV2CardsUpdatePostRequestInnerCharacteristicsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ContentV2CardsUpdatePostRequestInnerCharacteristicsInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUpdatePostRequestInnerCharacteristicsInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ContentV2CardsUpdatePostRequestInnerCharacteristicsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ContentV2CardsUpdatePostRequestInnerCharacteristicsInner) SetId(v int32) {
	o.Id = &v
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContentV2CardsUpdatePostRequestInnerCharacteristicsInner) GetValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContentV2CardsUpdatePostRequestInnerCharacteristicsInner) GetValueOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return &o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ContentV2CardsUpdatePostRequestInnerCharacteristicsInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given interface{} and assigns it to the Value field.
func (o *ContentV2CardsUpdatePostRequestInnerCharacteristicsInner) SetValue(v interface{}) {
	o.Value = v
}

func (o ContentV2CardsUpdatePostRequestInnerCharacteristicsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentV2CardsUpdatePostRequestInnerCharacteristicsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableContentV2CardsUpdatePostRequestInnerCharacteristicsInner struct {
	value *ContentV2CardsUpdatePostRequestInnerCharacteristicsInner
	isSet bool
}

func (v NullableContentV2CardsUpdatePostRequestInnerCharacteristicsInner) Get() *ContentV2CardsUpdatePostRequestInnerCharacteristicsInner {
	return v.value
}

func (v *NullableContentV2CardsUpdatePostRequestInnerCharacteristicsInner) Set(val *ContentV2CardsUpdatePostRequestInnerCharacteristicsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableContentV2CardsUpdatePostRequestInnerCharacteristicsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableContentV2CardsUpdatePostRequestInnerCharacteristicsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentV2CardsUpdatePostRequestInnerCharacteristicsInner(val *ContentV2CardsUpdatePostRequestInnerCharacteristicsInner) *NullableContentV2CardsUpdatePostRequestInnerCharacteristicsInner {
	return &NullableContentV2CardsUpdatePostRequestInnerCharacteristicsInner{value: val, isSet: true}
}

func (v NullableContentV2CardsUpdatePostRequestInnerCharacteristicsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentV2CardsUpdatePostRequestInnerCharacteristicsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
