/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ContentV2GetCardsListPostRequestSettingsSort type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentV2GetCardsListPostRequestSettingsSort{}

// ContentV2GetCardsListPostRequestSettingsSort Параметр сортировки
type ContentV2GetCardsListPostRequestSettingsSort struct {
	// Сортировать по полю **updatedAt** (`false` - по убыванию, `true` - по возрастанию)
	Ascending *bool `json:"ascending,omitempty"`
}

// NewContentV2GetCardsListPostRequestSettingsSort instantiates a new ContentV2GetCardsListPostRequestSettingsSort object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentV2GetCardsListPostRequestSettingsSort() *ContentV2GetCardsListPostRequestSettingsSort {
	this := ContentV2GetCardsListPostRequestSettingsSort{}
	return &this
}

// NewContentV2GetCardsListPostRequestSettingsSortWithDefaults instantiates a new ContentV2GetCardsListPostRequestSettingsSort object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentV2GetCardsListPostRequestSettingsSortWithDefaults() *ContentV2GetCardsListPostRequestSettingsSort {
	this := ContentV2GetCardsListPostRequestSettingsSort{}
	return &this
}

// GetAscending returns the Ascending field value if set, zero value otherwise.
func (o *ContentV2GetCardsListPostRequestSettingsSort) GetAscending() bool {
	if o == nil || IsNil(o.Ascending) {
		var ret bool
		return ret
	}
	return *o.Ascending
}

// GetAscendingOk returns a tuple with the Ascending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2GetCardsListPostRequestSettingsSort) GetAscendingOk() (*bool, bool) {
	if o == nil || IsNil(o.Ascending) {
		return nil, false
	}
	return o.Ascending, true
}

// HasAscending returns a boolean if a field has been set.
func (o *ContentV2GetCardsListPostRequestSettingsSort) HasAscending() bool {
	if o != nil && !IsNil(o.Ascending) {
		return true
	}

	return false
}

// SetAscending gets a reference to the given bool and assigns it to the Ascending field.
func (o *ContentV2GetCardsListPostRequestSettingsSort) SetAscending(v bool) {
	o.Ascending = &v
}

func (o ContentV2GetCardsListPostRequestSettingsSort) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentV2GetCardsListPostRequestSettingsSort) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ascending) {
		toSerialize["ascending"] = o.Ascending
	}
	return toSerialize, nil
}

type NullableContentV2GetCardsListPostRequestSettingsSort struct {
	value *ContentV2GetCardsListPostRequestSettingsSort
	isSet bool
}

func (v NullableContentV2GetCardsListPostRequestSettingsSort) Get() *ContentV2GetCardsListPostRequestSettingsSort {
	return v.value
}

func (v *NullableContentV2GetCardsListPostRequestSettingsSort) Set(val *ContentV2GetCardsListPostRequestSettingsSort) {
	v.value = val
	v.isSet = true
}

func (v NullableContentV2GetCardsListPostRequestSettingsSort) IsSet() bool {
	return v.isSet
}

func (v *NullableContentV2GetCardsListPostRequestSettingsSort) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentV2GetCardsListPostRequestSettingsSort(val *ContentV2GetCardsListPostRequestSettingsSort) *NullableContentV2GetCardsListPostRequestSettingsSort {
	return &NullableContentV2GetCardsListPostRequestSettingsSort{value: val, isSet: true}
}

func (v NullableContentV2GetCardsListPostRequestSettingsSort) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentV2GetCardsListPostRequestSettingsSort) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
