/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ContentV2BarcodesPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentV2BarcodesPostRequest{}

// ContentV2BarcodesPostRequest struct for ContentV2BarcodesPostRequest
type ContentV2BarcodesPostRequest struct {
	// Кол-во баркодов которые надо сгенерировать, максимальное доступное количество баркодов для генерации - `5 000`
	Count *int32 `json:"count,omitempty"`
}

// NewContentV2BarcodesPostRequest instantiates a new ContentV2BarcodesPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentV2BarcodesPostRequest() *ContentV2BarcodesPostRequest {
	this := ContentV2BarcodesPostRequest{}
	return &this
}

// NewContentV2BarcodesPostRequestWithDefaults instantiates a new ContentV2BarcodesPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentV2BarcodesPostRequestWithDefaults() *ContentV2BarcodesPostRequest {
	this := ContentV2BarcodesPostRequest{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *ContentV2BarcodesPostRequest) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2BarcodesPostRequest) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *ContentV2BarcodesPostRequest) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *ContentV2BarcodesPostRequest) SetCount(v int32) {
	o.Count = &v
}

func (o ContentV2BarcodesPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentV2BarcodesPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableContentV2BarcodesPostRequest struct {
	value *ContentV2BarcodesPostRequest
	isSet bool
}

func (v NullableContentV2BarcodesPostRequest) Get() *ContentV2BarcodesPostRequest {
	return v.value
}

func (v *NullableContentV2BarcodesPostRequest) Set(val *ContentV2BarcodesPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableContentV2BarcodesPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableContentV2BarcodesPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentV2BarcodesPostRequest(val *ContentV2BarcodesPostRequest) *NullableContentV2BarcodesPostRequest {
	return &NullableContentV2BarcodesPostRequest{value: val, isSet: true}
}

func (v NullableContentV2BarcodesPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentV2BarcodesPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
