/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ContentV2GetCardsListPost200ResponseCursor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentV2GetCardsListPost200ResponseCursor{}

// ContentV2GetCardsListPost200ResponseCursor Пагинатор
type ContentV2GetCardsListPost200ResponseCursor struct {
	// Дата с которой надо запрашивать следующий список КТ
	UpdatedAt *string `json:"updatedAt,omitempty"`
	// Номер Артикула WB с которой надо запрашивать следующий список КТ
	NmID *int32 `json:"nmID,omitempty"`
	// Кол-во возвращенных КТ
	Total *int32 `json:"total,omitempty"`
}

// NewContentV2GetCardsListPost200ResponseCursor instantiates a new ContentV2GetCardsListPost200ResponseCursor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentV2GetCardsListPost200ResponseCursor() *ContentV2GetCardsListPost200ResponseCursor {
	this := ContentV2GetCardsListPost200ResponseCursor{}
	return &this
}

// NewContentV2GetCardsListPost200ResponseCursorWithDefaults instantiates a new ContentV2GetCardsListPost200ResponseCursor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentV2GetCardsListPost200ResponseCursorWithDefaults() *ContentV2GetCardsListPost200ResponseCursor {
	this := ContentV2GetCardsListPost200ResponseCursor{}
	return &this
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ContentV2GetCardsListPost200ResponseCursor) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2GetCardsListPost200ResponseCursor) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ContentV2GetCardsListPost200ResponseCursor) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ContentV2GetCardsListPost200ResponseCursor) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetNmID returns the NmID field value if set, zero value otherwise.
func (o *ContentV2GetCardsListPost200ResponseCursor) GetNmID() int32 {
	if o == nil || IsNil(o.NmID) {
		var ret int32
		return ret
	}
	return *o.NmID
}

// GetNmIDOk returns a tuple with the NmID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2GetCardsListPost200ResponseCursor) GetNmIDOk() (*int32, bool) {
	if o == nil || IsNil(o.NmID) {
		return nil, false
	}
	return o.NmID, true
}

// HasNmID returns a boolean if a field has been set.
func (o *ContentV2GetCardsListPost200ResponseCursor) HasNmID() bool {
	if o != nil && !IsNil(o.NmID) {
		return true
	}

	return false
}

// SetNmID gets a reference to the given int32 and assigns it to the NmID field.
func (o *ContentV2GetCardsListPost200ResponseCursor) SetNmID(v int32) {
	o.NmID = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ContentV2GetCardsListPost200ResponseCursor) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2GetCardsListPost200ResponseCursor) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ContentV2GetCardsListPost200ResponseCursor) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ContentV2GetCardsListPost200ResponseCursor) SetTotal(v int32) {
	o.Total = &v
}

func (o ContentV2GetCardsListPost200ResponseCursor) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentV2GetCardsListPost200ResponseCursor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.NmID) {
		toSerialize["nmID"] = o.NmID
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableContentV2GetCardsListPost200ResponseCursor struct {
	value *ContentV2GetCardsListPost200ResponseCursor
	isSet bool
}

func (v NullableContentV2GetCardsListPost200ResponseCursor) Get() *ContentV2GetCardsListPost200ResponseCursor {
	return v.value
}

func (v *NullableContentV2GetCardsListPost200ResponseCursor) Set(val *ContentV2GetCardsListPost200ResponseCursor) {
	v.value = val
	v.isSet = true
}

func (v NullableContentV2GetCardsListPost200ResponseCursor) IsSet() bool {
	return v.isSet
}

func (v *NullableContentV2GetCardsListPost200ResponseCursor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentV2GetCardsListPost200ResponseCursor(val *ContentV2GetCardsListPost200ResponseCursor) *NullableContentV2GetCardsListPost200ResponseCursor {
	return &NullableContentV2GetCardsListPost200ResponseCursor{value: val, isSet: true}
}

func (v NullableContentV2GetCardsListPost200ResponseCursor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentV2GetCardsListPost200ResponseCursor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
