/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ContentV2GetCardsTrashPostRequestSettingsCursor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentV2GetCardsTrashPostRequestSettingsCursor{}

// ContentV2GetCardsTrashPostRequestSettingsCursor Курсор
type ContentV2GetCardsTrashPostRequestSettingsCursor struct {
	// Сколько КТ выдать в ответе
	Limit *int32 `json:"limit,omitempty"`
}

// NewContentV2GetCardsTrashPostRequestSettingsCursor instantiates a new ContentV2GetCardsTrashPostRequestSettingsCursor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentV2GetCardsTrashPostRequestSettingsCursor() *ContentV2GetCardsTrashPostRequestSettingsCursor {
	this := ContentV2GetCardsTrashPostRequestSettingsCursor{}
	return &this
}

// NewContentV2GetCardsTrashPostRequestSettingsCursorWithDefaults instantiates a new ContentV2GetCardsTrashPostRequestSettingsCursor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentV2GetCardsTrashPostRequestSettingsCursorWithDefaults() *ContentV2GetCardsTrashPostRequestSettingsCursor {
	this := ContentV2GetCardsTrashPostRequestSettingsCursor{}
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *ContentV2GetCardsTrashPostRequestSettingsCursor) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2GetCardsTrashPostRequestSettingsCursor) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *ContentV2GetCardsTrashPostRequestSettingsCursor) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *ContentV2GetCardsTrashPostRequestSettingsCursor) SetLimit(v int32) {
	o.Limit = &v
}

func (o ContentV2GetCardsTrashPostRequestSettingsCursor) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentV2GetCardsTrashPostRequestSettingsCursor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	return toSerialize, nil
}

type NullableContentV2GetCardsTrashPostRequestSettingsCursor struct {
	value *ContentV2GetCardsTrashPostRequestSettingsCursor
	isSet bool
}

func (v NullableContentV2GetCardsTrashPostRequestSettingsCursor) Get() *ContentV2GetCardsTrashPostRequestSettingsCursor {
	return v.value
}

func (v *NullableContentV2GetCardsTrashPostRequestSettingsCursor) Set(val *ContentV2GetCardsTrashPostRequestSettingsCursor) {
	v.value = val
	v.isSet = true
}

func (v NullableContentV2GetCardsTrashPostRequestSettingsCursor) IsSet() bool {
	return v.isSet
}

func (v *NullableContentV2GetCardsTrashPostRequestSettingsCursor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentV2GetCardsTrashPostRequestSettingsCursor(val *ContentV2GetCardsTrashPostRequestSettingsCursor) *NullableContentV2GetCardsTrashPostRequestSettingsCursor {
	return &NullableContentV2GetCardsTrashPostRequestSettingsCursor{value: val, isSet: true}
}

func (v NullableContentV2GetCardsTrashPostRequestSettingsCursor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentV2GetCardsTrashPostRequestSettingsCursor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
