/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ContentV2CardsErrorListGet200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentV2CardsErrorListGet200ResponseDataInner{}

// ContentV2CardsErrorListGet200ResponseDataInner struct for ContentV2CardsErrorListGet200ResponseDataInner
type ContentV2CardsErrorListGet200ResponseDataInner struct {
	// Категория для который создавалось КТ с данной НМ
	Object *string `json:"object,omitempty"`
	// Артикул продавца
	VendorCode *string `json:"vendorCode,omitempty"`
	// Дата и время запроса на создание КТ с данным НМ
	UpdateAt *string `json:"updateAt,omitempty"`
	// Список ошибок из-за которых не обработался запрос на создание КТ с данным НМ
	Errors []string `json:"errors,omitempty"`
	// Идентификатор предмета
	ObjectID *int32 `json:"objectID,omitempty"`
}

// NewContentV2CardsErrorListGet200ResponseDataInner instantiates a new ContentV2CardsErrorListGet200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentV2CardsErrorListGet200ResponseDataInner() *ContentV2CardsErrorListGet200ResponseDataInner {
	this := ContentV2CardsErrorListGet200ResponseDataInner{}
	return &this
}

// NewContentV2CardsErrorListGet200ResponseDataInnerWithDefaults instantiates a new ContentV2CardsErrorListGet200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentV2CardsErrorListGet200ResponseDataInnerWithDefaults() *ContentV2CardsErrorListGet200ResponseDataInner {
	this := ContentV2CardsErrorListGet200ResponseDataInner{}
	return &this
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) SetObject(v string) {
	o.Object = &v
}

// GetVendorCode returns the VendorCode field value if set, zero value otherwise.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) GetVendorCode() string {
	if o == nil || IsNil(o.VendorCode) {
		var ret string
		return ret
	}
	return *o.VendorCode
}

// GetVendorCodeOk returns a tuple with the VendorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) GetVendorCodeOk() (*string, bool) {
	if o == nil || IsNil(o.VendorCode) {
		return nil, false
	}
	return o.VendorCode, true
}

// HasVendorCode returns a boolean if a field has been set.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) HasVendorCode() bool {
	if o != nil && !IsNil(o.VendorCode) {
		return true
	}

	return false
}

// SetVendorCode gets a reference to the given string and assigns it to the VendorCode field.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) SetVendorCode(v string) {
	o.VendorCode = &v
}

// GetUpdateAt returns the UpdateAt field value if set, zero value otherwise.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) GetUpdateAt() string {
	if o == nil || IsNil(o.UpdateAt) {
		var ret string
		return ret
	}
	return *o.UpdateAt
}

// GetUpdateAtOk returns a tuple with the UpdateAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) GetUpdateAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdateAt) {
		return nil, false
	}
	return o.UpdateAt, true
}

// HasUpdateAt returns a boolean if a field has been set.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) HasUpdateAt() bool {
	if o != nil && !IsNil(o.UpdateAt) {
		return true
	}

	return false
}

// SetUpdateAt gets a reference to the given string and assigns it to the UpdateAt field.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) SetUpdateAt(v string) {
	o.UpdateAt = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) SetErrors(v []string) {
	o.Errors = v
}

// GetObjectID returns the ObjectID field value if set, zero value otherwise.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) GetObjectID() int32 {
	if o == nil || IsNil(o.ObjectID) {
		var ret int32
		return ret
	}
	return *o.ObjectID
}

// GetObjectIDOk returns a tuple with the ObjectID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) GetObjectIDOk() (*int32, bool) {
	if o == nil || IsNil(o.ObjectID) {
		return nil, false
	}
	return o.ObjectID, true
}

// HasObjectID returns a boolean if a field has been set.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) HasObjectID() bool {
	if o != nil && !IsNil(o.ObjectID) {
		return true
	}

	return false
}

// SetObjectID gets a reference to the given int32 and assigns it to the ObjectID field.
func (o *ContentV2CardsErrorListGet200ResponseDataInner) SetObjectID(v int32) {
	o.ObjectID = &v
}

func (o ContentV2CardsErrorListGet200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentV2CardsErrorListGet200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	if !IsNil(o.VendorCode) {
		toSerialize["vendorCode"] = o.VendorCode
	}
	if !IsNil(o.UpdateAt) {
		toSerialize["updateAt"] = o.UpdateAt
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.ObjectID) {
		toSerialize["objectID"] = o.ObjectID
	}
	return toSerialize, nil
}

type NullableContentV2CardsErrorListGet200ResponseDataInner struct {
	value *ContentV2CardsErrorListGet200ResponseDataInner
	isSet bool
}

func (v NullableContentV2CardsErrorListGet200ResponseDataInner) Get() *ContentV2CardsErrorListGet200ResponseDataInner {
	return v.value
}

func (v *NullableContentV2CardsErrorListGet200ResponseDataInner) Set(val *ContentV2CardsErrorListGet200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableContentV2CardsErrorListGet200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableContentV2CardsErrorListGet200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentV2CardsErrorListGet200ResponseDataInner(val *ContentV2CardsErrorListGet200ResponseDataInner) *NullableContentV2CardsErrorListGet200ResponseDataInner {
	return &NullableContentV2CardsErrorListGet200ResponseDataInner{value: val, isSet: true}
}

func (v NullableContentV2CardsErrorListGet200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentV2CardsErrorListGet200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
