/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ContentV2CardsDeleteTrashPostRequestInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentV2CardsDeleteTrashPostRequestInner{}

// ContentV2CardsDeleteTrashPostRequestInner struct for ContentV2CardsDeleteTrashPostRequestInner
type ContentV2CardsDeleteTrashPostRequestInner struct {
	// Артикул WB (max. 1000)
	NmIDs []int32 `json:"nmIDs,omitempty"`
}

// NewContentV2CardsDeleteTrashPostRequestInner instantiates a new ContentV2CardsDeleteTrashPostRequestInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentV2CardsDeleteTrashPostRequestInner() *ContentV2CardsDeleteTrashPostRequestInner {
	this := ContentV2CardsDeleteTrashPostRequestInner{}
	return &this
}

// NewContentV2CardsDeleteTrashPostRequestInnerWithDefaults instantiates a new ContentV2CardsDeleteTrashPostRequestInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentV2CardsDeleteTrashPostRequestInnerWithDefaults() *ContentV2CardsDeleteTrashPostRequestInner {
	this := ContentV2CardsDeleteTrashPostRequestInner{}
	return &this
}

// GetNmIDs returns the NmIDs field value if set, zero value otherwise.
func (o *ContentV2CardsDeleteTrashPostRequestInner) GetNmIDs() []int32 {
	if o == nil || IsNil(o.NmIDs) {
		var ret []int32
		return ret
	}
	return o.NmIDs
}

// GetNmIDsOk returns a tuple with the NmIDs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsDeleteTrashPostRequestInner) GetNmIDsOk() ([]int32, bool) {
	if o == nil || IsNil(o.NmIDs) {
		return nil, false
	}
	return o.NmIDs, true
}

// HasNmIDs returns a boolean if a field has been set.
func (o *ContentV2CardsDeleteTrashPostRequestInner) HasNmIDs() bool {
	if o != nil && !IsNil(o.NmIDs) {
		return true
	}

	return false
}

// SetNmIDs gets a reference to the given []int32 and assigns it to the NmIDs field.
func (o *ContentV2CardsDeleteTrashPostRequestInner) SetNmIDs(v []int32) {
	o.NmIDs = v
}

func (o ContentV2CardsDeleteTrashPostRequestInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentV2CardsDeleteTrashPostRequestInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NmIDs) {
		toSerialize["nmIDs"] = o.NmIDs
	}
	return toSerialize, nil
}

type NullableContentV2CardsDeleteTrashPostRequestInner struct {
	value *ContentV2CardsDeleteTrashPostRequestInner
	isSet bool
}

func (v NullableContentV2CardsDeleteTrashPostRequestInner) Get() *ContentV2CardsDeleteTrashPostRequestInner {
	return v.value
}

func (v *NullableContentV2CardsDeleteTrashPostRequestInner) Set(val *ContentV2CardsDeleteTrashPostRequestInner) {
	v.value = val
	v.isSet = true
}

func (v NullableContentV2CardsDeleteTrashPostRequestInner) IsSet() bool {
	return v.isSet
}

func (v *NullableContentV2CardsDeleteTrashPostRequestInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentV2CardsDeleteTrashPostRequestInner(val *ContentV2CardsDeleteTrashPostRequestInner) *NullableContentV2CardsDeleteTrashPostRequestInner {
	return &NullableContentV2CardsDeleteTrashPostRequestInner{value: val, isSet: true}
}

func (v NullableContentV2CardsDeleteTrashPostRequestInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentV2CardsDeleteTrashPostRequestInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
