/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ContentV2CardsUploadPost413Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentV2CardsUploadPost413Response{}

// ContentV2CardsUploadPost413Response struct for ContentV2CardsUploadPost413Response
type ContentV2CardsUploadPost413Response struct {
	// Заголовок ошибки
	Title *string `json:"title,omitempty"`
	// Детали ошибки
	Detail *string `json:"detail,omitempty"`
	// Внутренний код ошибки
	Code *string `json:"code,omitempty"`
	// Уникальный ID запроса
	RequestId *string `json:"requestId,omitempty"`
	// ID внутреннего сервиса WB
	Origin *string `json:"origin,omitempty"`
	// HTTP статус-код
	Status *float32 `json:"status,omitempty"`
	// Расшифровка HTTP статус-кода
	StatusText *string `json:"statusText,omitempty"`
}

// NewContentV2CardsUploadPost413Response instantiates a new ContentV2CardsUploadPost413Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentV2CardsUploadPost413Response() *ContentV2CardsUploadPost413Response {
	this := ContentV2CardsUploadPost413Response{}
	return &this
}

// NewContentV2CardsUploadPost413ResponseWithDefaults instantiates a new ContentV2CardsUploadPost413Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentV2CardsUploadPost413ResponseWithDefaults() *ContentV2CardsUploadPost413Response {
	this := ContentV2CardsUploadPost413Response{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ContentV2CardsUploadPost413Response) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadPost413Response) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ContentV2CardsUploadPost413Response) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ContentV2CardsUploadPost413Response) SetTitle(v string) {
	o.Title = &v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *ContentV2CardsUploadPost413Response) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadPost413Response) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *ContentV2CardsUploadPost413Response) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *ContentV2CardsUploadPost413Response) SetDetail(v string) {
	o.Detail = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ContentV2CardsUploadPost413Response) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadPost413Response) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ContentV2CardsUploadPost413Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ContentV2CardsUploadPost413Response) SetCode(v string) {
	o.Code = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *ContentV2CardsUploadPost413Response) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadPost413Response) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *ContentV2CardsUploadPost413Response) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *ContentV2CardsUploadPost413Response) SetRequestId(v string) {
	o.RequestId = &v
}

// GetOrigin returns the Origin field value if set, zero value otherwise.
func (o *ContentV2CardsUploadPost413Response) GetOrigin() string {
	if o == nil || IsNil(o.Origin) {
		var ret string
		return ret
	}
	return *o.Origin
}

// GetOriginOk returns a tuple with the Origin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadPost413Response) GetOriginOk() (*string, bool) {
	if o == nil || IsNil(o.Origin) {
		return nil, false
	}
	return o.Origin, true
}

// HasOrigin returns a boolean if a field has been set.
func (o *ContentV2CardsUploadPost413Response) HasOrigin() bool {
	if o != nil && !IsNil(o.Origin) {
		return true
	}

	return false
}

// SetOrigin gets a reference to the given string and assigns it to the Origin field.
func (o *ContentV2CardsUploadPost413Response) SetOrigin(v string) {
	o.Origin = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ContentV2CardsUploadPost413Response) GetStatus() float32 {
	if o == nil || IsNil(o.Status) {
		var ret float32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadPost413Response) GetStatusOk() (*float32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ContentV2CardsUploadPost413Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given float32 and assigns it to the Status field.
func (o *ContentV2CardsUploadPost413Response) SetStatus(v float32) {
	o.Status = &v
}

// GetStatusText returns the StatusText field value if set, zero value otherwise.
func (o *ContentV2CardsUploadPost413Response) GetStatusText() string {
	if o == nil || IsNil(o.StatusText) {
		var ret string
		return ret
	}
	return *o.StatusText
}

// GetStatusTextOk returns a tuple with the StatusText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadPost413Response) GetStatusTextOk() (*string, bool) {
	if o == nil || IsNil(o.StatusText) {
		return nil, false
	}
	return o.StatusText, true
}

// HasStatusText returns a boolean if a field has been set.
func (o *ContentV2CardsUploadPost413Response) HasStatusText() bool {
	if o != nil && !IsNil(o.StatusText) {
		return true
	}

	return false
}

// SetStatusText gets a reference to the given string and assigns it to the StatusText field.
func (o *ContentV2CardsUploadPost413Response) SetStatusText(v string) {
	o.StatusText = &v
}

func (o ContentV2CardsUploadPost413Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentV2CardsUploadPost413Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if !IsNil(o.Origin) {
		toSerialize["origin"] = o.Origin
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusText) {
		toSerialize["statusText"] = o.StatusText
	}
	return toSerialize, nil
}

type NullableContentV2CardsUploadPost413Response struct {
	value *ContentV2CardsUploadPost413Response
	isSet bool
}

func (v NullableContentV2CardsUploadPost413Response) Get() *ContentV2CardsUploadPost413Response {
	return v.value
}

func (v *NullableContentV2CardsUploadPost413Response) Set(val *ContentV2CardsUploadPost413Response) {
	v.value = val
	v.isSet = true
}

func (v NullableContentV2CardsUploadPost413Response) IsSet() bool {
	return v.isSet
}

func (v *NullableContentV2CardsUploadPost413Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentV2CardsUploadPost413Response(val *ContentV2CardsUploadPost413Response) *NullableContentV2CardsUploadPost413Response {
	return &NullableContentV2CardsUploadPost413Response{value: val, isSet: true}
}

func (v NullableContentV2CardsUploadPost413Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentV2CardsUploadPost413Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
