/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ContentV2GetCardsListPost200ResponseCardsInnerTagsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentV2GetCardsListPost200ResponseCardsInnerTagsInner{}

// ContentV2GetCardsListPost200ResponseCardsInnerTagsInner struct for ContentV2GetCardsListPost200ResponseCardsInnerTagsInner
type ContentV2GetCardsListPost200ResponseCardsInnerTagsInner struct {
	// Идентификатор тега
	Id *int32 `json:"id,omitempty"`
	// Название тега
	Name *string `json:"name,omitempty"`
	// Цвет тега. <dl> <dt>Доступные цвета:</dt> <dd><code>D1CFD7</code> - серый</dd> <dd><code>FEE0E0</code> - красный</dd> <dd><code>ECDAFF</code> - фиолетовый</dd> <dd><code>E4EAFF</code> - синий</dd> <dd><code>DEF1DD</code> - зеленый</dd> <dd><code>FFECC7</code> - желтый</dd> </dl>
	Color *string `json:"color,omitempty"`
}

// NewContentV2GetCardsListPost200ResponseCardsInnerTagsInner instantiates a new ContentV2GetCardsListPost200ResponseCardsInnerTagsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentV2GetCardsListPost200ResponseCardsInnerTagsInner() *ContentV2GetCardsListPost200ResponseCardsInnerTagsInner {
	this := ContentV2GetCardsListPost200ResponseCardsInnerTagsInner{}
	return &this
}

// NewContentV2GetCardsListPost200ResponseCardsInnerTagsInnerWithDefaults instantiates a new ContentV2GetCardsListPost200ResponseCardsInnerTagsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentV2GetCardsListPost200ResponseCardsInnerTagsInnerWithDefaults() *ContentV2GetCardsListPost200ResponseCardsInnerTagsInner {
	this := ContentV2GetCardsListPost200ResponseCardsInnerTagsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ContentV2GetCardsListPost200ResponseCardsInnerTagsInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2GetCardsListPost200ResponseCardsInnerTagsInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ContentV2GetCardsListPost200ResponseCardsInnerTagsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ContentV2GetCardsListPost200ResponseCardsInnerTagsInner) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ContentV2GetCardsListPost200ResponseCardsInnerTagsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2GetCardsListPost200ResponseCardsInnerTagsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ContentV2GetCardsListPost200ResponseCardsInnerTagsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ContentV2GetCardsListPost200ResponseCardsInnerTagsInner) SetName(v string) {
	o.Name = &v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *ContentV2GetCardsListPost200ResponseCardsInnerTagsInner) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2GetCardsListPost200ResponseCardsInnerTagsInner) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *ContentV2GetCardsListPost200ResponseCardsInnerTagsInner) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *ContentV2GetCardsListPost200ResponseCardsInnerTagsInner) SetColor(v string) {
	o.Color = &v
}

func (o ContentV2GetCardsListPost200ResponseCardsInnerTagsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentV2GetCardsListPost200ResponseCardsInnerTagsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	return toSerialize, nil
}

type NullableContentV2GetCardsListPost200ResponseCardsInnerTagsInner struct {
	value *ContentV2GetCardsListPost200ResponseCardsInnerTagsInner
	isSet bool
}

func (v NullableContentV2GetCardsListPost200ResponseCardsInnerTagsInner) Get() *ContentV2GetCardsListPost200ResponseCardsInnerTagsInner {
	return v.value
}

func (v *NullableContentV2GetCardsListPost200ResponseCardsInnerTagsInner) Set(val *ContentV2GetCardsListPost200ResponseCardsInnerTagsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableContentV2GetCardsListPost200ResponseCardsInnerTagsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableContentV2GetCardsListPost200ResponseCardsInnerTagsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentV2GetCardsListPost200ResponseCardsInnerTagsInner(val *ContentV2GetCardsListPost200ResponseCardsInnerTagsInner) *NullableContentV2GetCardsListPost200ResponseCardsInnerTagsInner {
	return &NullableContentV2GetCardsListPost200ResponseCardsInnerTagsInner{value: val, isSet: true}
}

func (v NullableContentV2GetCardsListPost200ResponseCardsInnerTagsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentV2GetCardsListPost200ResponseCardsInnerTagsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
