/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ContentV2TagIdPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentV2TagIdPatchRequest{}

// ContentV2TagIdPatchRequest struct for ContentV2TagIdPatchRequest
type ContentV2TagIdPatchRequest struct {
	// Цвет тега
	Color *string `json:"color,omitempty"`
	// Имя тега
	Name *string `json:"name,omitempty"`
}

// NewContentV2TagIdPatchRequest instantiates a new ContentV2TagIdPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentV2TagIdPatchRequest() *ContentV2TagIdPatchRequest {
	this := ContentV2TagIdPatchRequest{}
	return &this
}

// NewContentV2TagIdPatchRequestWithDefaults instantiates a new ContentV2TagIdPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentV2TagIdPatchRequestWithDefaults() *ContentV2TagIdPatchRequest {
	this := ContentV2TagIdPatchRequest{}
	return &this
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *ContentV2TagIdPatchRequest) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2TagIdPatchRequest) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *ContentV2TagIdPatchRequest) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *ContentV2TagIdPatchRequest) SetColor(v string) {
	o.Color = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ContentV2TagIdPatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2TagIdPatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ContentV2TagIdPatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ContentV2TagIdPatchRequest) SetName(v string) {
	o.Name = &v
}

func (o ContentV2TagIdPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentV2TagIdPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableContentV2TagIdPatchRequest struct {
	value *ContentV2TagIdPatchRequest
	isSet bool
}

func (v NullableContentV2TagIdPatchRequest) Get() *ContentV2TagIdPatchRequest {
	return v.value
}

func (v *NullableContentV2TagIdPatchRequest) Set(val *ContentV2TagIdPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableContentV2TagIdPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableContentV2TagIdPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentV2TagIdPatchRequest(val *ContentV2TagIdPatchRequest) *NullableContentV2TagIdPatchRequest {
	return &NullableContentV2TagIdPatchRequest{value: val, isSet: true}
}

func (v NullableContentV2TagIdPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentV2TagIdPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
