/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ResponseCardCreateAdditionalErrorsOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseCardCreateAdditionalErrorsOneOf{}

// ResponseCardCreateAdditionalErrorsOneOf struct for ResponseCardCreateAdditionalErrorsOneOf
type ResponseCardCreateAdditionalErrorsOneOf struct {
	String *string `json:"string,omitempty"`
}

// NewResponseCardCreateAdditionalErrorsOneOf instantiates a new ResponseCardCreateAdditionalErrorsOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseCardCreateAdditionalErrorsOneOf() *ResponseCardCreateAdditionalErrorsOneOf {
	this := ResponseCardCreateAdditionalErrorsOneOf{}
	return &this
}

// NewResponseCardCreateAdditionalErrorsOneOfWithDefaults instantiates a new ResponseCardCreateAdditionalErrorsOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseCardCreateAdditionalErrorsOneOfWithDefaults() *ResponseCardCreateAdditionalErrorsOneOf {
	this := ResponseCardCreateAdditionalErrorsOneOf{}
	return &this
}

// GetString returns the String field value if set, zero value otherwise.
func (o *ResponseCardCreateAdditionalErrorsOneOf) GetString() string {
	if o == nil || IsNil(o.String) {
		var ret string
		return ret
	}
	return *o.String
}

// GetStringOk returns a tuple with the String field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCardCreateAdditionalErrorsOneOf) GetStringOk() (*string, bool) {
	if o == nil || IsNil(o.String) {
		return nil, false
	}
	return o.String, true
}

// HasString returns a boolean if a field has been set.
func (o *ResponseCardCreateAdditionalErrorsOneOf) HasString() bool {
	if o != nil && !IsNil(o.String) {
		return true
	}

	return false
}

// SetString gets a reference to the given string and assigns it to the String field.
func (o *ResponseCardCreateAdditionalErrorsOneOf) SetString(v string) {
	o.String = &v
}

func (o ResponseCardCreateAdditionalErrorsOneOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseCardCreateAdditionalErrorsOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.String) {
		toSerialize["string"] = o.String
	}
	return toSerialize, nil
}

type NullableResponseCardCreateAdditionalErrorsOneOf struct {
	value *ResponseCardCreateAdditionalErrorsOneOf
	isSet bool
}

func (v NullableResponseCardCreateAdditionalErrorsOneOf) Get() *ResponseCardCreateAdditionalErrorsOneOf {
	return v.value
}

func (v *NullableResponseCardCreateAdditionalErrorsOneOf) Set(val *ResponseCardCreateAdditionalErrorsOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseCardCreateAdditionalErrorsOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseCardCreateAdditionalErrorsOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseCardCreateAdditionalErrorsOneOf(val *ResponseCardCreateAdditionalErrorsOneOf) *NullableResponseCardCreateAdditionalErrorsOneOf {
	return &NullableResponseCardCreateAdditionalErrorsOneOf{value: val, isSet: true}
}

func (v NullableResponseCardCreateAdditionalErrorsOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseCardCreateAdditionalErrorsOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
