/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ResponseBodyContentError400AdditionalErrors type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseBodyContentError400AdditionalErrors{}

// ResponseBodyContentError400AdditionalErrors Дополнительные ошибки
type ResponseBodyContentError400AdditionalErrors struct {
	MoveNmsToTrash *string `json:"MoveNmsToTrash,omitempty"`
}

// NewResponseBodyContentError400AdditionalErrors instantiates a new ResponseBodyContentError400AdditionalErrors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseBodyContentError400AdditionalErrors() *ResponseBodyContentError400AdditionalErrors {
	this := ResponseBodyContentError400AdditionalErrors{}
	return &this
}

// NewResponseBodyContentError400AdditionalErrorsWithDefaults instantiates a new ResponseBodyContentError400AdditionalErrors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseBodyContentError400AdditionalErrorsWithDefaults() *ResponseBodyContentError400AdditionalErrors {
	this := ResponseBodyContentError400AdditionalErrors{}
	return &this
}

// GetMoveNmsToTrash returns the MoveNmsToTrash field value if set, zero value otherwise.
func (o *ResponseBodyContentError400AdditionalErrors) GetMoveNmsToTrash() string {
	if o == nil || IsNil(o.MoveNmsToTrash) {
		var ret string
		return ret
	}
	return *o.MoveNmsToTrash
}

// GetMoveNmsToTrashOk returns a tuple with the MoveNmsToTrash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseBodyContentError400AdditionalErrors) GetMoveNmsToTrashOk() (*string, bool) {
	if o == nil || IsNil(o.MoveNmsToTrash) {
		return nil, false
	}
	return o.MoveNmsToTrash, true
}

// HasMoveNmsToTrash returns a boolean if a field has been set.
func (o *ResponseBodyContentError400AdditionalErrors) HasMoveNmsToTrash() bool {
	if o != nil && !IsNil(o.MoveNmsToTrash) {
		return true
	}

	return false
}

// SetMoveNmsToTrash gets a reference to the given string and assigns it to the MoveNmsToTrash field.
func (o *ResponseBodyContentError400AdditionalErrors) SetMoveNmsToTrash(v string) {
	o.MoveNmsToTrash = &v
}

func (o ResponseBodyContentError400AdditionalErrors) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseBodyContentError400AdditionalErrors) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MoveNmsToTrash) {
		toSerialize["MoveNmsToTrash"] = o.MoveNmsToTrash
	}
	return toSerialize, nil
}

type NullableResponseBodyContentError400AdditionalErrors struct {
	value *ResponseBodyContentError400AdditionalErrors
	isSet bool
}

func (v NullableResponseBodyContentError400AdditionalErrors) Get() *ResponseBodyContentError400AdditionalErrors {
	return v.value
}

func (v *NullableResponseBodyContentError400AdditionalErrors) Set(val *ResponseBodyContentError400AdditionalErrors) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseBodyContentError400AdditionalErrors) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseBodyContentError400AdditionalErrors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseBodyContentError400AdditionalErrors(val *ResponseBodyContentError400AdditionalErrors) *NullableResponseBodyContentError400AdditionalErrors {
	return &NullableResponseBodyContentError400AdditionalErrors{value: val, isSet: true}
}

func (v NullableResponseBodyContentError400AdditionalErrors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseBodyContentError400AdditionalErrors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
