/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ResponseContentError6 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseContentError6{}

// ResponseContentError6 struct for ResponseContentError6
type ResponseContentError6 struct {
	Data map[string]interface{} `json:"data,omitempty"`
	// Флаг ошибки
	Error *bool `json:"error,omitempty"`
	// Описание ошибки
	ErrorText *string `json:"errorText,omitempty"`
	// Дополнительные ошибки
	AdditionalErrors NullableString `json:"additionalErrors,omitempty"`
}

// NewResponseContentError6 instantiates a new ResponseContentError6 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseContentError6() *ResponseContentError6 {
	this := ResponseContentError6{}
	return &this
}

// NewResponseContentError6WithDefaults instantiates a new ResponseContentError6 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseContentError6WithDefaults() *ResponseContentError6 {
	this := ResponseContentError6{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResponseContentError6) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponseContentError6) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ResponseContentError6) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *ResponseContentError6) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ResponseContentError6) GetError() bool {
	if o == nil || IsNil(o.Error) {
		var ret bool
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseContentError6) GetErrorOk() (*bool, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ResponseContentError6) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given bool and assigns it to the Error field.
func (o *ResponseContentError6) SetError(v bool) {
	o.Error = &v
}

// GetErrorText returns the ErrorText field value if set, zero value otherwise.
func (o *ResponseContentError6) GetErrorText() string {
	if o == nil || IsNil(o.ErrorText) {
		var ret string
		return ret
	}
	return *o.ErrorText
}

// GetErrorTextOk returns a tuple with the ErrorText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseContentError6) GetErrorTextOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorText) {
		return nil, false
	}
	return o.ErrorText, true
}

// HasErrorText returns a boolean if a field has been set.
func (o *ResponseContentError6) HasErrorText() bool {
	if o != nil && !IsNil(o.ErrorText) {
		return true
	}

	return false
}

// SetErrorText gets a reference to the given string and assigns it to the ErrorText field.
func (o *ResponseContentError6) SetErrorText(v string) {
	o.ErrorText = &v
}

// GetAdditionalErrors returns the AdditionalErrors field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResponseContentError6) GetAdditionalErrors() string {
	if o == nil || IsNil(o.AdditionalErrors.Get()) {
		var ret string
		return ret
	}
	return *o.AdditionalErrors.Get()
}

// GetAdditionalErrorsOk returns a tuple with the AdditionalErrors field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponseContentError6) GetAdditionalErrorsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AdditionalErrors.Get(), o.AdditionalErrors.IsSet()
}

// HasAdditionalErrors returns a boolean if a field has been set.
func (o *ResponseContentError6) HasAdditionalErrors() bool {
	if o != nil && o.AdditionalErrors.IsSet() {
		return true
	}

	return false
}

// SetAdditionalErrors gets a reference to the given NullableString and assigns it to the AdditionalErrors field.
func (o *ResponseContentError6) SetAdditionalErrors(v string) {
	o.AdditionalErrors.Set(&v)
}

// SetAdditionalErrorsNil sets the value for AdditionalErrors to be an explicit nil
func (o *ResponseContentError6) SetAdditionalErrorsNil() {
	o.AdditionalErrors.Set(nil)
}

// UnsetAdditionalErrors ensures that no value is present for AdditionalErrors, not even an explicit nil
func (o *ResponseContentError6) UnsetAdditionalErrors() {
	o.AdditionalErrors.Unset()
}

func (o ResponseContentError6) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseContentError6) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.ErrorText) {
		toSerialize["errorText"] = o.ErrorText
	}
	if o.AdditionalErrors.IsSet() {
		toSerialize["additionalErrors"] = o.AdditionalErrors.Get()
	}
	return toSerialize, nil
}

type NullableResponseContentError6 struct {
	value *ResponseContentError6
	isSet bool
}

func (v NullableResponseContentError6) Get() *ResponseContentError6 {
	return v.value
}

func (v *NullableResponseContentError6) Set(val *ResponseContentError6) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseContentError6) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseContentError6) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseContentError6(val *ResponseContentError6) *NullableResponseContentError6 {
	return &NullableResponseContentError6{value: val, isSet: true}
}

func (v NullableResponseContentError6) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseContentError6) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
