/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ResponseContentError5AdditionalErrors type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseContentError5AdditionalErrors{}

// ResponseContentError5AdditionalErrors Дополнительные ошибки
type ResponseContentError5AdditionalErrors struct {
	TagID *string `json:"tagID,omitempty"`
}

// NewResponseContentError5AdditionalErrors instantiates a new ResponseContentError5AdditionalErrors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseContentError5AdditionalErrors() *ResponseContentError5AdditionalErrors {
	this := ResponseContentError5AdditionalErrors{}
	return &this
}

// NewResponseContentError5AdditionalErrorsWithDefaults instantiates a new ResponseContentError5AdditionalErrors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseContentError5AdditionalErrorsWithDefaults() *ResponseContentError5AdditionalErrors {
	this := ResponseContentError5AdditionalErrors{}
	return &this
}

// GetTagID returns the TagID field value if set, zero value otherwise.
func (o *ResponseContentError5AdditionalErrors) GetTagID() string {
	if o == nil || IsNil(o.TagID) {
		var ret string
		return ret
	}
	return *o.TagID
}

// GetTagIDOk returns a tuple with the TagID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseContentError5AdditionalErrors) GetTagIDOk() (*string, bool) {
	if o == nil || IsNil(o.TagID) {
		return nil, false
	}
	return o.TagID, true
}

// HasTagID returns a boolean if a field has been set.
func (o *ResponseContentError5AdditionalErrors) HasTagID() bool {
	if o != nil && !IsNil(o.TagID) {
		return true
	}

	return false
}

// SetTagID gets a reference to the given string and assigns it to the TagID field.
func (o *ResponseContentError5AdditionalErrors) SetTagID(v string) {
	o.TagID = &v
}

func (o ResponseContentError5AdditionalErrors) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseContentError5AdditionalErrors) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TagID) {
		toSerialize["tagID"] = o.TagID
	}
	return toSerialize, nil
}

type NullableResponseContentError5AdditionalErrors struct {
	value *ResponseContentError5AdditionalErrors
	isSet bool
}

func (v NullableResponseContentError5AdditionalErrors) Get() *ResponseContentError5AdditionalErrors {
	return v.value
}

func (v *NullableResponseContentError5AdditionalErrors) Set(val *ResponseContentError5AdditionalErrors) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseContentError5AdditionalErrors) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseContentError5AdditionalErrors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseContentError5AdditionalErrors(val *ResponseContentError5AdditionalErrors) *NullableResponseContentError5AdditionalErrors {
	return &NullableResponseContentError5AdditionalErrors{value: val, isSet: true}
}

func (v NullableResponseContentError5AdditionalErrors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseContentError5AdditionalErrors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
