/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ContentV2CardsUploadAddPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentV2CardsUploadAddPostRequest{}

// ContentV2CardsUploadAddPostRequest struct for ContentV2CardsUploadAddPostRequest
type ContentV2CardsUploadAddPostRequest struct {
	// imtID КТ, к которой добавляется НМ
	ImtID *int32 `json:"imtID,omitempty"`
	// Структура добавляемой НМ
	CardsToAdd []ContentV2CardsUploadAddPostRequestCardsToAddInner `json:"cardsToAdd,omitempty"`
}

// NewContentV2CardsUploadAddPostRequest instantiates a new ContentV2CardsUploadAddPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentV2CardsUploadAddPostRequest() *ContentV2CardsUploadAddPostRequest {
	this := ContentV2CardsUploadAddPostRequest{}
	return &this
}

// NewContentV2CardsUploadAddPostRequestWithDefaults instantiates a new ContentV2CardsUploadAddPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentV2CardsUploadAddPostRequestWithDefaults() *ContentV2CardsUploadAddPostRequest {
	this := ContentV2CardsUploadAddPostRequest{}
	return &this
}

// GetImtID returns the ImtID field value if set, zero value otherwise.
func (o *ContentV2CardsUploadAddPostRequest) GetImtID() int32 {
	if o == nil || IsNil(o.ImtID) {
		var ret int32
		return ret
	}
	return *o.ImtID
}

// GetImtIDOk returns a tuple with the ImtID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadAddPostRequest) GetImtIDOk() (*int32, bool) {
	if o == nil || IsNil(o.ImtID) {
		return nil, false
	}
	return o.ImtID, true
}

// HasImtID returns a boolean if a field has been set.
func (o *ContentV2CardsUploadAddPostRequest) HasImtID() bool {
	if o != nil && !IsNil(o.ImtID) {
		return true
	}

	return false
}

// SetImtID gets a reference to the given int32 and assigns it to the ImtID field.
func (o *ContentV2CardsUploadAddPostRequest) SetImtID(v int32) {
	o.ImtID = &v
}

// GetCardsToAdd returns the CardsToAdd field value if set, zero value otherwise.
func (o *ContentV2CardsUploadAddPostRequest) GetCardsToAdd() []ContentV2CardsUploadAddPostRequestCardsToAddInner {
	if o == nil || IsNil(o.CardsToAdd) {
		var ret []ContentV2CardsUploadAddPostRequestCardsToAddInner
		return ret
	}
	return o.CardsToAdd
}

// GetCardsToAddOk returns a tuple with the CardsToAdd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadAddPostRequest) GetCardsToAddOk() ([]ContentV2CardsUploadAddPostRequestCardsToAddInner, bool) {
	if o == nil || IsNil(o.CardsToAdd) {
		return nil, false
	}
	return o.CardsToAdd, true
}

// HasCardsToAdd returns a boolean if a field has been set.
func (o *ContentV2CardsUploadAddPostRequest) HasCardsToAdd() bool {
	if o != nil && !IsNil(o.CardsToAdd) {
		return true
	}

	return false
}

// SetCardsToAdd gets a reference to the given []ContentV2CardsUploadAddPostRequestCardsToAddInner and assigns it to the CardsToAdd field.
func (o *ContentV2CardsUploadAddPostRequest) SetCardsToAdd(v []ContentV2CardsUploadAddPostRequestCardsToAddInner) {
	o.CardsToAdd = v
}

func (o ContentV2CardsUploadAddPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentV2CardsUploadAddPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ImtID) {
		toSerialize["imtID"] = o.ImtID
	}
	if !IsNil(o.CardsToAdd) {
		toSerialize["cardsToAdd"] = o.CardsToAdd
	}
	return toSerialize, nil
}

type NullableContentV2CardsUploadAddPostRequest struct {
	value *ContentV2CardsUploadAddPostRequest
	isSet bool
}

func (v NullableContentV2CardsUploadAddPostRequest) Get() *ContentV2CardsUploadAddPostRequest {
	return v.value
}

func (v *NullableContentV2CardsUploadAddPostRequest) Set(val *ContentV2CardsUploadAddPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableContentV2CardsUploadAddPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableContentV2CardsUploadAddPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentV2CardsUploadAddPostRequest(val *ContentV2CardsUploadAddPostRequest) *NullableContentV2CardsUploadAddPostRequest {
	return &NullableContentV2CardsUploadAddPostRequest{value: val, isSet: true}
}

func (v NullableContentV2CardsUploadAddPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentV2CardsUploadAddPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
