/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ResponseContentError4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseContentError4{}

// ResponseContentError4 struct for ResponseContentError4
type ResponseContentError4 struct {
	Data map[string]interface{} `json:"data,omitempty"`
	// Флаг ошибки
	Error *bool `json:"error,omitempty"`
	// Описание ошибки
	ErrorText        *string                                `json:"errorText,omitempty"`
	AdditionalErrors *ResponseContentError4AdditionalErrors `json:"additionalErrors,omitempty"`
}

// NewResponseContentError4 instantiates a new ResponseContentError4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseContentError4() *ResponseContentError4 {
	this := ResponseContentError4{}
	return &this
}

// NewResponseContentError4WithDefaults instantiates a new ResponseContentError4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseContentError4WithDefaults() *ResponseContentError4 {
	this := ResponseContentError4{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResponseContentError4) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponseContentError4) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ResponseContentError4) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *ResponseContentError4) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ResponseContentError4) GetError() bool {
	if o == nil || IsNil(o.Error) {
		var ret bool
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseContentError4) GetErrorOk() (*bool, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ResponseContentError4) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given bool and assigns it to the Error field.
func (o *ResponseContentError4) SetError(v bool) {
	o.Error = &v
}

// GetErrorText returns the ErrorText field value if set, zero value otherwise.
func (o *ResponseContentError4) GetErrorText() string {
	if o == nil || IsNil(o.ErrorText) {
		var ret string
		return ret
	}
	return *o.ErrorText
}

// GetErrorTextOk returns a tuple with the ErrorText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseContentError4) GetErrorTextOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorText) {
		return nil, false
	}
	return o.ErrorText, true
}

// HasErrorText returns a boolean if a field has been set.
func (o *ResponseContentError4) HasErrorText() bool {
	if o != nil && !IsNil(o.ErrorText) {
		return true
	}

	return false
}

// SetErrorText gets a reference to the given string and assigns it to the ErrorText field.
func (o *ResponseContentError4) SetErrorText(v string) {
	o.ErrorText = &v
}

// GetAdditionalErrors returns the AdditionalErrors field value if set, zero value otherwise.
func (o *ResponseContentError4) GetAdditionalErrors() ResponseContentError4AdditionalErrors {
	if o == nil || IsNil(o.AdditionalErrors) {
		var ret ResponseContentError4AdditionalErrors
		return ret
	}
	return *o.AdditionalErrors
}

// GetAdditionalErrorsOk returns a tuple with the AdditionalErrors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseContentError4) GetAdditionalErrorsOk() (*ResponseContentError4AdditionalErrors, bool) {
	if o == nil || IsNil(o.AdditionalErrors) {
		return nil, false
	}
	return o.AdditionalErrors, true
}

// HasAdditionalErrors returns a boolean if a field has been set.
func (o *ResponseContentError4) HasAdditionalErrors() bool {
	if o != nil && !IsNil(o.AdditionalErrors) {
		return true
	}

	return false
}

// SetAdditionalErrors gets a reference to the given ResponseContentError4AdditionalErrors and assigns it to the AdditionalErrors field.
func (o *ResponseContentError4) SetAdditionalErrors(v ResponseContentError4AdditionalErrors) {
	o.AdditionalErrors = &v
}

func (o ResponseContentError4) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseContentError4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.ErrorText) {
		toSerialize["errorText"] = o.ErrorText
	}
	if !IsNil(o.AdditionalErrors) {
		toSerialize["additionalErrors"] = o.AdditionalErrors
	}
	return toSerialize, nil
}

type NullableResponseContentError4 struct {
	value *ResponseContentError4
	isSet bool
}

func (v NullableResponseContentError4) Get() *ResponseContentError4 {
	return v.value
}

func (v *NullableResponseContentError4) Set(val *ResponseContentError4) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseContentError4) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseContentError4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseContentError4(val *ResponseContentError4) *NullableResponseContentError4 {
	return &NullableResponseContentError4{value: val, isSet: true}
}

func (v NullableResponseContentError4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseContentError4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
