/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ContentV2TagsGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentV2TagsGet200ResponseData{}

// ContentV2TagsGet200ResponseData struct for ContentV2TagsGet200ResponseData
type ContentV2TagsGet200ResponseData struct {
	// Числовой идентификатор тега
	Id *int32 `json:"id,omitempty"`
	// Цвет тега
	Color *string `json:"color,omitempty"`
	// Имя тега
	Name *string `json:"name,omitempty"`
}

// NewContentV2TagsGet200ResponseData instantiates a new ContentV2TagsGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentV2TagsGet200ResponseData() *ContentV2TagsGet200ResponseData {
	this := ContentV2TagsGet200ResponseData{}
	return &this
}

// NewContentV2TagsGet200ResponseDataWithDefaults instantiates a new ContentV2TagsGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentV2TagsGet200ResponseDataWithDefaults() *ContentV2TagsGet200ResponseData {
	this := ContentV2TagsGet200ResponseData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ContentV2TagsGet200ResponseData) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2TagsGet200ResponseData) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ContentV2TagsGet200ResponseData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ContentV2TagsGet200ResponseData) SetId(v int32) {
	o.Id = &v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *ContentV2TagsGet200ResponseData) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2TagsGet200ResponseData) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *ContentV2TagsGet200ResponseData) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *ContentV2TagsGet200ResponseData) SetColor(v string) {
	o.Color = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ContentV2TagsGet200ResponseData) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2TagsGet200ResponseData) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ContentV2TagsGet200ResponseData) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ContentV2TagsGet200ResponseData) SetName(v string) {
	o.Name = &v
}

func (o ContentV2TagsGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentV2TagsGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableContentV2TagsGet200ResponseData struct {
	value *ContentV2TagsGet200ResponseData
	isSet bool
}

func (v NullableContentV2TagsGet200ResponseData) Get() *ContentV2TagsGet200ResponseData {
	return v.value
}

func (v *NullableContentV2TagsGet200ResponseData) Set(val *ContentV2TagsGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableContentV2TagsGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableContentV2TagsGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentV2TagsGet200ResponseData(val *ContentV2TagsGet200ResponseData) *NullableContentV2TagsGet200ResponseData {
	return &NullableContentV2TagsGet200ResponseData{value: val, isSet: true}
}

func (v NullableContentV2TagsGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentV2TagsGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
