/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner{}

// ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner struct for ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner
type ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner struct {
	// Идентификатор характеристики
	Id int32 `json:"id"`
	// Значение характеристики. Тип значения зависит от типа характеристики
	Value interface{} `json:"value"`
}

type _ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner

// NewContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner instantiates a new ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner(id int32, value interface{}) *ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner {
	this := ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner{}
	this.Id = id
	this.Value = value
	return &this
}

// NewContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInnerWithDefaults instantiates a new ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInnerWithDefaults() *ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner {
	this := ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner{}
	return &this
}

// GetId returns the Id field value
func (o *ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner) SetId(v int32) {
	o.Id = v
}

// GetValue returns the Value field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner) GetValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner) GetValueOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner) SetValue(v interface{}) {
	o.Value = v
}

func (o ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

func (o *ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner := _ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner)

	if err != nil {
		return err
	}

	*o = ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner(varContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner)

	return err
}

type NullableContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner struct {
	value *ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner
	isSet bool
}

func (v NullableContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner) Get() *ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner {
	return v.value
}

func (v *NullableContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner) Set(val *ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner(val *ContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner) *NullableContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner {
	return &NullableContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner{value: val, isSet: true}
}

func (v NullableContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentV2CardsUploadPostRequestInnerVariantsInnerCharacteristicsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
