/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ContentV2TagPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentV2TagPostRequest{}

// ContentV2TagPostRequest struct for ContentV2TagPostRequest
type ContentV2TagPostRequest struct {
	// Цвет тега. <dl> <dt>Доступные цвета:</dt> <dd><code>D1CFD7</code> - серый</dd> <dd><code>FEE0E0</code> - красный</dd> <dd><code>ECDAFF</code> - фиолетовый</dd> <dd><code>E4EAFF</code> - синий</dd> <dd><code>DEF1DD</code> - зеленый</dd> <dd><code>FFECC7</code> - желтый</dd> </dl>
	Color *string `json:"color,omitempty"`
	// Имя тега
	Name *string `json:"name,omitempty"`
}

// NewContentV2TagPostRequest instantiates a new ContentV2TagPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentV2TagPostRequest() *ContentV2TagPostRequest {
	this := ContentV2TagPostRequest{}
	return &this
}

// NewContentV2TagPostRequestWithDefaults instantiates a new ContentV2TagPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentV2TagPostRequestWithDefaults() *ContentV2TagPostRequest {
	this := ContentV2TagPostRequest{}
	return &this
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *ContentV2TagPostRequest) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2TagPostRequest) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *ContentV2TagPostRequest) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *ContentV2TagPostRequest) SetColor(v string) {
	o.Color = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ContentV2TagPostRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2TagPostRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ContentV2TagPostRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ContentV2TagPostRequest) SetName(v string) {
	o.Name = &v
}

func (o ContentV2TagPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentV2TagPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableContentV2TagPostRequest struct {
	value *ContentV2TagPostRequest
	isSet bool
}

func (v NullableContentV2TagPostRequest) Get() *ContentV2TagPostRequest {
	return v.value
}

func (v *NullableContentV2TagPostRequest) Set(val *ContentV2TagPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableContentV2TagPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableContentV2TagPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentV2TagPostRequest(val *ContentV2TagPostRequest) *NullableContentV2TagPostRequest {
	return &NullableContentV2TagPostRequest{value: val, isSet: true}
}

func (v NullableContentV2TagPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentV2TagPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
