/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions{}

// ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions Габариты упаковки товара. Указывать в **сантиметрах** для любого товара.  <br>  Если не указать структуру dimensions в запросе, то она сгенерируется системой автоматически с нулевыми значениями длины, ширины, высоты
type ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions struct {
	// Длина, см
	Length *int32 `json:"length,omitempty"`
	// Ширина, см
	Width *int32 `json:"width,omitempty"`
	// Высота, см
	Height *int32 `json:"height,omitempty"`
}

// NewContentV2CardsUploadPostRequestInnerVariantsInnerDimensions instantiates a new ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentV2CardsUploadPostRequestInnerVariantsInnerDimensions() *ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions {
	this := ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions{}
	return &this
}

// NewContentV2CardsUploadPostRequestInnerVariantsInnerDimensionsWithDefaults instantiates a new ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentV2CardsUploadPostRequestInnerVariantsInnerDimensionsWithDefaults() *ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions {
	this := ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions{}
	return &this
}

// GetLength returns the Length field value if set, zero value otherwise.
func (o *ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) GetLength() int32 {
	if o == nil || IsNil(o.Length) {
		var ret int32
		return ret
	}
	return *o.Length
}

// GetLengthOk returns a tuple with the Length field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) GetLengthOk() (*int32, bool) {
	if o == nil || IsNil(o.Length) {
		return nil, false
	}
	return o.Length, true
}

// HasLength returns a boolean if a field has been set.
func (o *ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) HasLength() bool {
	if o != nil && !IsNil(o.Length) {
		return true
	}

	return false
}

// SetLength gets a reference to the given int32 and assigns it to the Length field.
func (o *ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) SetLength(v int32) {
	o.Length = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) GetWidth() int32 {
	if o == nil || IsNil(o.Width) {
		var ret int32
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) GetWidthOk() (*int32, bool) {
	if o == nil || IsNil(o.Width) {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) HasWidth() bool {
	if o != nil && !IsNil(o.Width) {
		return true
	}

	return false
}

// SetWidth gets a reference to the given int32 and assigns it to the Width field.
func (o *ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) SetWidth(v int32) {
	o.Width = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) GetHeight() int32 {
	if o == nil || IsNil(o.Height) {
		var ret int32
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) GetHeightOk() (*int32, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int32 and assigns it to the Height field.
func (o *ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) SetHeight(v int32) {
	o.Height = &v
}

func (o ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Length) {
		toSerialize["length"] = o.Length
	}
	if !IsNil(o.Width) {
		toSerialize["width"] = o.Width
	}
	if !IsNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	return toSerialize, nil
}

type NullableContentV2CardsUploadPostRequestInnerVariantsInnerDimensions struct {
	value *ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions
	isSet bool
}

func (v NullableContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) Get() *ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions {
	return v.value
}

func (v *NullableContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) Set(val *ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) {
	v.value = val
	v.isSet = true
}

func (v NullableContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) IsSet() bool {
	return v.isSet
}

func (v *NullableContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentV2CardsUploadPostRequestInnerVariantsInnerDimensions(val *ContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) *NullableContentV2CardsUploadPostRequestInnerVariantsInnerDimensions {
	return &NullableContentV2CardsUploadPostRequestInnerVariantsInnerDimensions{value: val, isSet: true}
}

func (v NullableContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentV2CardsUploadPostRequestInnerVariantsInnerDimensions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
