/*
Описание API Контента

 <dl> <dt>Словарь сокращений:</dt> <dd>КТ — карточка товара</dd> <dd>НМ — номенклатура</dd> </dl> Ограничения по количеству запросов: <dd>Допускается максимум 100 запросов в минуту на методы контента в целом.</dd>  <br> Публичное API Контента создано для синхронизации данных между серверами Wildberries и серверами продавцов. <br> Вы загружаете данные на свои носители, работаете с ними на своих мощностях и синхронизируетесь с нашими серверами по мере необходимости. <br> <code>Не допускается использование API Контента в качестве внешней базы данных. При превышении лимитов на запросы доступ к API будет ограничен.</code> <br>  <br>

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentapi

import (
	"encoding/json"
)

// checks if the ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner{}

// ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner struct for ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner
type ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner struct {
	Id    *int32   `json:"id,omitempty"`
	Name  *string  `json:"name,omitempty"`
	Value []string `json:"value,omitempty"`
}

// NewContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner instantiates a new ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner() *ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner {
	this := ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner{}
	return &this
}

// NewContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInnerWithDefaults instantiates a new ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInnerWithDefaults() *ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner {
	this := ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) GetValue() []string {
	if o == nil || IsNil(o.Value) {
		var ret []string
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) GetValueOk() ([]string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given []string and assigns it to the Value field.
func (o *ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) SetValue(v []string) {
	o.Value = v
}

func (o ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner struct {
	value *ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner
	isSet bool
}

func (v NullableContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) Get() *ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner {
	return v.value
}

func (v *NullableContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) Set(val *ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner(val *ContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) *NullableContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner {
	return &NullableContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner{value: val, isSet: true}
}

func (v NullableContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentV2GetCardsTrashPost200ResponseCardsInnerCharacteristicsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
