name: Deploy to Digital Ocean App Platform

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - SHT**


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: marketplace-api-dev
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}